openebs/node-disk-manager

- Makefile
- cmd/app/command/commands.go
- cmd/app/command/device-list.go
- cmd/app/command/device.go
- cmd/app/command/start.go
- hack/build.sh
- Changed Makefile and hack/build.sh to create binary named "ndm" instead of "ndmctl"
- Changed all references of "ndmctl" to "ndm" in code.
- Changed Makefile to build docker image
Signed-off-by: Abhishek Kashyap <abhishek.kashyap@mayadata.io>
> Changed ndmctl to ndm

- .travis.yml
- Dockerfile.in
- Makefile
- hack/build.sh
- pkg/apis/ndm/v1alpha1/register.go
- pkg/apis/ndm/v1alpha1/types.go
Fixes : #8 
- This PR will add a dockerfile which uses a configurable base image defined in makefile
- It will define a base image in makefile
- It will add vet, fmt ,go test, etc in makefile to run whille building an image
Signed-off-by: sagarkrsd <sagar.kumar@openebs.io>
> Add a dockerfile and .travis.yml to build node-disk-manager

- .travis.yml
- cmd/app/command/commands.go
- cmd/app/command/start.go
- cmd/controller/ctrl.go
- cmd/types/v1/block_device_info.go
- pkg/apis/ndm/v1alpha1/types.go
- pkg/server/metrics_uptime_test.go
- pkg/server/server.go
- pkg/util/util.go
Signed-off-by: Pawan <pawanprakash101@gmail.com>
> fixing travis build

- .gitignore
- .travis.yml
- Makefile
- hack/test.sh
Fix #35 
Signed-off-by: Shovan <shovan.cse91@gmail.com>
> add codecov

- README.md
Add CI,codecov,goreport and license batches to readme file
Changes committed:
modified:   README.md
Signed-off-by: sagarkrsd <sagar.kumar@openebs.io>
> Add CI,codecov,goreport and license batches to readme file

- Makefile
- hack/build.sh
- hack/test.sh
- hack/update-codegen.sh
- This PR intends to modularize build script by splitting it into various functions so that it become more readable and understandable.
fixes: #57 
Signed-off-by: sagarkrsd <sagar.kumar@openebs.io>
> Modularize build script by splitting it into different functions

- cmd/controller/controller.go
As part of the initial startup, if the disk CRDs are not loaded,
the discovery process fails due to errors in updating. A restart
will be required to fix this after the disk CRDs are available in
etcd.
Signed-off-by: kmova <kiran.mova@openebs.io>
> fix(startup): wait for disk crd to be loaded before scanning disks

- pkg/smart/mockdata.go
Fixes #92 
Signed-off-by: Debasish Sahoo <debasish.sahoo1998@gmail.com>
> Fixed lint error in mockdata.go

- integration_test/ndm_util/ndm_util.go
Signed-off-by: Tommaso Garuglieri <garuglieritommaso@gmail.com>
Fix: #112
> Fixed ineffassign lint error

- pkg/apis/openebs.io/register.go
fixes #102 
fix lint error by adding the comment on exported const group name
Signed-off-by: Andrea Thniah <andreathniah@gmail.com>
> Fix lint error in register.go

- cmd/app/command/commands.go
fixes #95 
fix lint errors
Signed-off-by: Nathan Seebarran <nathan.seebarran@gmail.com>
> style(ndm): fix lint errors in commands.go

- integration_test/ndm_util/ndm_util.go
closes #108 
- Fixes typos in ndm_util.go
> style(ndm): Fixes typos in ndm_util.go

- pkg/util/fdutil_test.go
https://github.com/openebs/node-disk-manager/issues/111
Signed-off-by: bege13mot <bege13mot@gmail.com>
> style(ndm): Fix go vet errors in fdutil_test.go

- pkg/apis/openebs.io/v1alpha1/register.go
PR https://github.com/openebs/node-disk-manager/issues/99
> style(ndm): Fix lint in pkg/apis/openebs.io/v1alpha1/register.go

- pkg/util/util.go
> style(ndm): add description to Hash method in util.go

- pkg/server/metrics.go
https://github.com/openebs/node-disk-manager/issues/96
Signed-off-by: bege13mot <bege13mot@gmail.com>
> style(ndm): Fix warnings pkg/server/metrics.go

- cmd/controller/filter.go
This PR fixes lint errors in filter.go (Line 31 and 52). It fixes #106 
Signed-off-by: gunjan01 <gunjan.tank9@gmail.com>
> style(ndm): Fixed lint errors - cmd/controller/filter.go

- pkg/smart/scsicommands.go
Fixes #105
Signed-off-by: Jean Morais jeancdemorais@gmail.com
> style(ndm): Fix lint errors in scsicommands.go

- .github/ISSUE_TEMPLATE/1_bug_report.md
- .github/ISSUE_TEMPLATE/2_feature_request.md
This PR adds selectable issue templates to the repository.
>  Add selectable issue templates

- .travis.yml
- Makefile
- hack/push
- integration_test/ndm_util/ndm_util.go
Refactor the code to push the images to the quay repo. The same script
used to push the images from other openebs repo is used.
Signed-off-by: kmova <kiran.mova@mayadata.io>
> feat(build): push docker images to quay repo

- cmd/controller/sparsefilegenerator.go
Fix lint error in sparsefilegenerator.go file #97
Signed-off-by: Alberto Viana <albertogviana@gmail.com>
> Fix lint error in sparsefilegenerator.go file #97

- README.md
Change spelling of "evaulating" to "evaluating".
> README.md : Fix typo

- pkg/controller/blockdeviceclaim/blockdeviceclaim_controller.go
Verification of capacity is now made only in auto mode. In manual mode, even if you don't specify a capacity, the block device can be claimed.
> fix(selection): capacity check is made only for auto-mode

- pkg/cleaner/jobcontroller.go
Sparse files will be now mounted inside the container and `dd` command will be issued on them. Sparse BDs can be claimed only in BlockMode.
> fix(cleaner): cleanup job to clean sparse block devices

- cmd/manager/main.go
- integration_tests/k8s/k8sndmresources.go
- integration_tests/sanity/deviceclaim_test.go
- integration_tests/yamls/clusterrole.yaml
- ndm-operator.yaml
- pkg/apis/openebs/v1alpha1/crds.go
- pkg/apis/openebs/v1alpha1/register.go
- pkg/controller/util.go
- pkg/crds/build.go
- pkg/crds/crd.go
- pkg/setup/build_crd.go
- pkg/setup/config.go
- pkg/setup/create_crd.go
- pkg/setup/install.go
automate installation of NDM Custom Resources(Disk, BlockDevice, BlockDeviceClaim) from NDM operator.
> feat(operator): automate installation of CRDs from NDM operator.

- pkg/controller/blockdeviceclaim/blockdeviceclaim_controller.go
To prevent accidental deletion of BDC, the BDC controller will now perform an additional check to make sure that the finalizer added by NDM will be the last one to be removed from the BDC object.
The new workflow will be:
- NDM Operator
1. NDM Operator will be watching all the BDCs
2. If DeletionTimeStamp is set on the BDC, then, Controller will check for the no.of finalizers on the BDC, if it has only one finalizer, then check whether NDM finalizer is present. If yes, the BD will be marked as released and the NDM finalizer will be removed.
3. NDM operator will make sure that, its finalizer is the last one to be removed from the BDC
- Maya (Owner of BDC)
1. Maya will create the BDC and add a finalizer to it.
2. When pool/localpv is deleted and cleanedup, this finalizer should be removed …
> fix(controller): add extra checks before removing finalizer

- integration_tests/k8s/k8sapi.go
Increased the timeout on BDDs so that flaky tests can be avoided.
> fix(BDD): increased time out for BDD

- pkg/controller/blockdevice/blockdevice_controller.go
- pkg/controller/blockdeviceclaim/blockdeviceclaim_controller.go
- pkg/controller/disk/disk_controller.go
Signed-off-by: Utkarsh Mani Tripathi <utkarsh.tripathi@mayadata.io>
> fix(log): remove unnecessary logs

- deploy/crds/openebs_v1alpha1_blockdeviceclaim_cr.yaml
make changes in sample BDC yaml with the latest updated BDC scheme.
> fix(yaml): fix sample BDC yaml with updated scheme

- pkg/cleaner/cleaner.go
fix cancelling of pending job for inactive BDs
> fix(cleaner): fix missing cancel job

- cmd/ndm_daemonset/controller/controller.go
- pkg/cleaner/jobcontroller.go
This PR fixes the hostname label on the cleanup job which was missed after the nodename refactoring in #296 
> fix(cleaner): fix missing label from cleanup job

- cmd/ndm_daemonset/controller/controller.go
Fix NodeHostName label used in controller to select the hostname of a node.
> fix(controller): fix node hostname label

- .travis.yml
- deploy/crds/openebs_v1alpha1_blockdevice_cr.yaml
- docs/developer-setup.md
- ndm-operator.yaml
1. Developer setup doc updated with seachest release version
2. changed label in blockdevice
3. removed cpu and memory for minikube vm driver=none
4. updated Daemonset to apps/v1
> fix(yaml,docs): fix issues in docs and yaml

- Makefile
fix script which assigns the image name, which will be pushed to docker hub and quay
> fix(Makefile): fixed script to push the image

- cmd/ndm_daemonset/app/command/commands.go
- cmd/ndm_daemonset/app/command/device-list.go
- cmd/ndm_daemonset/app/command/start.go
- cmd/ndm_daemonset/controller/controller.go
What this PR does / why we need it: Removes unused flags
Which issue this PR fixes : https://github.com/openebs/node-disk-manager/issues/324
Signed-off-by: Naveen Bellary <<bellary.naveen@gmail.com>>
> refactor: remove unused cobra flags.

- CHANGELOG.md
updated the changelogs with details of latest releases.
> chore(CHANGELOG): update the changelog with latest release

- cmd/ndm_daemonset/controller/blockdevicestore.go
- cmd/ndm_daemonset/controller/diskstore.go
moved to klog
Signed-off-by: moteesh <moteesh@gmail.com>
> logs formatted for easy parsing for sending alerts based on logs

- CHANGELOG.md
Added CHANGELOG for v0.4.4-RC2
> chore(CHANGELOG): add v0.4.4 changelog

- Makefile
change shellcheck version to stable.
> fix(Makefile): change shellcheck version

- cmd/ndm_daemonset/controller/blockdevicestore.go
- cmd/ndm_daemonset/controller/controller.go
- cmd/ndm_daemonset/controller/diskstore.go
- cmd/ndm_daemonset/controller/filter.go
- cmd/ndm_daemonset/controller/probe.go
- cmd/ndm_daemonset/controller/sparsefilegenerator.go
- cmd/ndm_daemonset/filter/filter.go
- cmd/ndm_daemonset/probe/capacityprobe.go
- cmd/ndm_daemonset/probe/eventhandler.go
- cmd/ndm_daemonset/probe/mountprobe.go
- cmd/ndm_daemonset/probe/probe.go
- cmd/ndm_daemonset/probe/seachestprobe.go
- cmd/ndm_daemonset/probe/smartprobe.go
- pkg/logs/logs.go
- pkg/select/blockdevice/filters.go
- pkg/udevevent/event.go
- pkg/udevevent/monitor.go
Signed-off-by: moteesh <moteesh@gmail.com>
> fixed missing spaces between keys in alertlogs

- Makefile
change shellcheck version to stable.
cherry-pick #342 
> cherry-pick(Makefile): change shellcheck version

- cmd/ndm-exporter/cmd/root.go
- cmd/ndm-exporter/main.go
- db/kubernetes/client.go
- ndm-exporter/collector/static.go
- ndm-exporter/exporter.go
changed some logs in ndm-exporter to klog.
> chore(log): change exporter logs to klog

- cmd/ndm_daemonset/controller/blockdevicestore.go
- cmd/ndm_daemonset/controller/controller.go
- cmd/ndm_daemonset/controller/diskstore.go
- cmd/ndm_daemonset/controller/filter.go
- cmd/ndm_daemonset/controller/probe.go
- cmd/ndm_daemonset/controller/sparsefilegenerator.go
- cmd/ndm_daemonset/filter/filter.go
- cmd/ndm_daemonset/probe/capacityprobe.go
- cmd/ndm_daemonset/probe/eventhandler.go
- cmd/ndm_daemonset/probe/mountprobe.go
- cmd/ndm_daemonset/probe/probe.go
- cmd/ndm_daemonset/probe/seachestprobe.go
- cmd/ndm_daemonset/probe/smartprobe.go
- pkg/logs/logs.go
- pkg/select/blockdevice/filters.go
- pkg/udevevent/event.go
- pkg/udevevent/monitor.go
* formatted alert logs with Infof and Errorf
Signed-off-by: moteesh <moteesh@gmail.com>
> fixed missing spaces between keys in alertlogs (#339)

- CHANGELOG.md
> chore(CHANGELOG): add v0.4.5-RC1 changelog

- docs/exporter.md
documentation steps to add a new metrics collector to the NDM exporter.
> docs(exporter): steps to add a new collector

- CHANGELOG.md
> chore(CHANGELOG): update changelog for v0.4.5

- pkg/crds/build.go
- pkg/setup/build_crd.go
- Add support for display PATH in Kubectl output
Cherry-picked PR: https://github.com/openebs/node-disk-manager/pull/366
Signed-off-by: chandan kumar <chandan.kr404@gmail.com>
> chore(bd): Add support for display PATH in kubectl output

- CHANGELOG.md
update CHANGELOG.md with latest release updates
> chore(CHANGELOG): update CHANGELOG with latest release updates

- CHANGELOG.md
update the CHANGELOG with v0.4.8-RC1 changes.
> chore(CHANGELOG): added 0.4.8-RC1 changelog

- vendor/github.com/diskfs/go-diskfs/disk/disk.go
- vendor/github.com/diskfs/go-diskfs/disk/disk_unix.go
- vendor/github.com/diskfs/go-diskfs/disk/disk_windows.go
update vendor with latest changes in diskfs to reread partition table
> chore(vendor): fix diskfs re-read partition table

- CHANGELOG.md
> chore(CHANGELOG): update changelog for v0.4.8

- .travis.yml
add recipients for receiving notifications from travis
> chore(travis): add recipients for travis notifications

- CONTRIBUTING.md
- README.md
- docs/design.md
- docs/developer-setup.md
- updated design docs
- update README and CONTRIBUTING guidelines
- updated information to build and test node-disk-manager
> fix(docs): update design docs, readme and contributing guidelines

- CHANGELOG.md
> chore(CHANGELOG): add changelog for v0.4.9

- .github/pull_request_template.md
- RELEASE.md
- fix invalid project tracker link
- add image names for NDM operator and NDM exporter
> docs(project): fix invalid links and image names in RELEASE file

- cmd/ndm_daemonset/controller/blockdevice.go
- cmd/ndm_daemonset/controller/blockdevicestore.go
- cmd/ndm_daemonset/controller/controller.go
- initialize namespace before setting on manager
- fix using namespace in Get() call
> fix(controller): fix using namespace in controller

- deploy/cluster_role.yaml
- deploy/cluster_role_binding.yaml
- deploy/crds/openebs_v1alpha1_blockdevice_cr.yaml
- deploy/crds/openebs_v1alpha1_blockdeviceclaim_cr.yaml
- deploy/ndm-cluster-exporter.yaml
- deploy/ndm-node-exporter.yaml
- deploy/node-disk-manager-config.yaml
- deploy/node-disk-manager.yaml
- deploy/node-disk-operator.yaml
- deploy/role.yaml
- deploy/role_binding.yaml
- deploy/service_account.yaml
- ndm-operator.yaml
fixes and refactors the deployment yamls given in the project. All the YAMLs have been updated with latest spec.
- add separate YAMLs to deploy each individual component
- fix sample YAMLs of BlockDevice and BlockDeviceClaim
- remove disks from ClusterRole
No
None
**Checklist:**
> chore(yaml): fix all the YAMLs to deploy NDM components

- docs/developer-setup.md
Updates the docs
Updates the developer documentation
No
N/A
N/A
**Checklist:**
> docs(update): Updating docs for go modules

- pkg/controller/blockdevice/blockdevice_controller.go
- pkg/controller/blockdevice/blockdevice_controller_test.go
- pkg/controller/blockdeviceclaim/blockdeviceclaim_controller.go
- pkg/controller/blockdeviceclaim/blockdeviceclaim_controller_test.go
Signed-off-by: Rahul M Chheda <rahul.chheda@mayadata.io>
**Checklist:**
Where:
* `fix`         - for bug fixes or improvements, not a fix for build script
* `chore`       - changes not related to production code
* `docs`        - …
> (feat) Added Events for BlockDevice Claims

- BUILD.md
- CONTRIBUTING.md
- README.md
- git-workflow.md
Docs change for better visibility
Moves dev docs to root directory of the repo
No
N/A
N/A
**Checklist:**
> docs(build): Moving developer setup to build.md

- .github/workflows/pull_request.yml
Shellcheck was failing in github actions for vendor directory
This PR excludes vendor directory 
No
This PR needs to be merged so that #433 can pass the github actions
**Checklist:**
> fix(lint): Vendor shellcheck fix for github action

- build/install-dep.sh
GIthub actions is not able to install packages from azure ubuntu repository. Hence builds are failing. This PR updates the repository before installing the dependencies. More info [here](https://github.com/actions/virtual-environments/issues/675#issuecomment-671027795)
Run `apt-get update` before installing dependencies
**Checklist:**
> fix(actions, build):  perform update before installing dependencies

- build/install-dep.sh
- run apt-get update before installing dependencies
Cherry-pick #471
> cherry-pick(actions, build): update repository before installing dependencies

- CONTRIBUTING.md
- docs/api-service-dev.md
- docs/api-service-user.md
Add docs for api-service
Add docs for api-service
No
#433 
**Checklist:**
> docs(api-service): Docs for api service

- .github/workflows/pull_request.yml
- Makefile
- build/build.sh
- build/install-dep.sh
- build/install-test-infra.sh
- build/integration-test.sh
- build/ndm-daemonset/entrypoint.sh
- build/test.sh
- build/update-codegen.sh
Signed-off-by: ajeetrai707 <ajeetrai707@gmail.com>
This PR is for license check. 
This PR checks license from makefile with different  go, shell , Dockerfiles.
If license found then build passes,else build fails 
Command to check license-check is `make license-check`
**Checklist:**
Where:
* `feat` …
> Add license-check for .go , .sh , Dockerfile

- .github/workflows/build.yml
This PR is to update  .github/workflows/build.yml for license-check 
This is for license-check if license found build passes else build fails. 
**Checklist:**
> Update .github/workflows/build.yml for license-check.

- changelogs/unreleased/404-akhilerm
- pkg/select/blockdevice/select.go
> fix(filter): add `block-device-tag` filter during manual claiming

- cmd/ndm_daemonset/probe/addhandler.go
- cmd/ndm_daemonset/probe/addhandler_test.go
- cmd/ndm_daemonset/probe/deletehandler_test.go
- cmd/ndm_daemonset/probe/eventhandler_test.go
- cmd/ndm_daemonset/probe/uuid.go
This PR add test cases for the add and delete event handler used in NDM.
- add test cases for delete handler
- add test cases for add handler
No
This PR contains only unit tests
**Checklist:**
> test(eventhandler) : add test cases for add and delete handler

- changelogs/unreleased/481-rahulchheda
- cmd/ndm_daemonset/filter/osdiskexcludefilter.go
- cmd/ndm_daemonset/filter/osdiskexcludefilter_test.go
Signed-off-by: Rahul M Chheda <rchheda@infracloud.io>
**Checklist:**
> fix(os-disk-exclude-filter) Exclude multiple os disk paths

- .github/workflows/build.yml
- .github/workflows/release.yml
- Makefile
- Makefile.buildx.mk
- build/ndm-daemonset/Dockerfile
- build/ndm-exporter/Dockerfile
- build/ndm-operator/Dockerfile
- fix release tag env in buildscript
- update github actions to remove deprecated methods
cherry-pick #507
> cherry-pick(build): fix build script and github actions

- deploy/helm/charts/Chart.yaml
- deploy/helm/charts/README.md
- deploy/helm/charts/templates/daemonset.yaml
- deploy/helm/charts/templates/deployment.yaml
- deploy/helm/charts/values.yaml
Using with syntax is preferrable as part of
best practice wherever possible as it is
more concise and clear
Signed-off-by: Ashutosh Kumar <sonasingh46@gmail.com>
> add 'with' syntax instead of 'if' in helm template and set seachest from default to false

- .github/workflows/chart-lint-test.yml
- .github/workflows/release-charts.yml
- deploy/helm/charts/Chart.yaml
- deploy/helm/charts/templates/NOTES.txt
This PR does the following:
1. Updates the chart releaser action version to v1.1.0
2. Provides the chart directory to the releaser action.
3. Indents NOTES.txt
Signed-off-by: Ashutosh Kumar <ashutosh.kumar@mayadata.io>
> fix(helm_release): update chart releaser image.

- deploy/helm/charts/Chart.yaml
- deploy/helm/charts/README.md
- deploy/helm/charts/values.yaml
> [stable/ndm]: update ndm charts to 1.0.1

- index.md
- add helm upgrade steps into helm repo webpage
Add upgrade steps to helm repo webpage
No
1. Install NDM helm charts 1.0.2
2. Apply the CRD yaml
3. Upgrade NDM helm charts to 1.1.0 and the CRDs will be upgraded.
This is a documentation change for upgrade steps.
**Checklist:**
> chore(website): add helm upgrade steps into helm repo

- deploy/helm/charts/Chart.yaml
- deploy/helm/charts/README.md
- deploy/helm/charts/crds/blockdevice.yaml
- deploy/helm/charts/crds/blockdeviceclaim.yaml
- deploy/helm/charts/templates/daemonset.yaml
- deploy/helm/charts/templates/deployment.yaml
- deploy/helm/charts/values.yaml
- update NDM daemonset and NDM operator
Documentation change for upgrade #533 
> [stable/ndm]: update ndm charts to 1.1.0

- blockdevice/blockdevice.go
- changelogs/unreleased/530-akhilerm
> feat(blockdevice, core): add mpath to supported DM device types (#530)

- deploy/helm/charts/Chart.yaml
- deploy/helm/charts/README.md
- deploy/helm/charts/values.yaml
> [stable/ndm]: update ndm charts to 1.1.1

- changelogs/unreleased/541-akhilerm
- deploy/crds/openebs.io_blockdevices_crd.yaml
- pkg/apis/openebs/v1alpha1/blockdevice_types.go
OpenAPI validation had a typo for SSD drive type
-fix typo in blockdevice API
No
**Checklist:**
> fix(api): fix typo in blockdevice API

- changelogs/unreleased/541-akhilerm
- deploy/crds/openebs.io_blockdevices_crd.yaml
- pkg/apis/openebs/v1alpha1/blockdevice_types.go
fix typo in blockdevice api validation
cherry-pick #541
> fix(api): fix typo in blockdevice API (#541)

- deploy/helm/charts/Chart.yaml
- deploy/helm/charts/README.md
- deploy/helm/charts/crds/blockdevice.yaml
- deploy/helm/charts/values.yaml
> [stable/ndm]: update ndm charts to 1.2.0

- .github/workflows/build.yml
- .github/workflows/release.yml
- set openebs as the default IMAGE_ORG in build and release workflow
No
Continuation of #544 
**Checklist:**
> chore(build): set default IMAGE_ORG as openebs

- .github/workflows/build.yml
- .github/workflows/pull_request.yml
- .github/workflows/release.yml
- Makefile
- add context to workflow
- remove RELEASE_TAG from makefile variables
continuation of https://github.com/openebs/node-disk-manager/pull/544
**Checklist:**
> fix(build): add context to workflow

- cmd/ndm_daemonset/probe/mountprobe_test.go
Fixes #253
Test coverage:
**Checklist:**
> test(mountprobe): Add unit tests for MountProbe

- deploy/helm/charts/Chart.yaml
- deploy/helm/charts/README.md
- deploy/helm/charts/values.yaml
> [stable/ndm]: update NDM charts to 1.3.0

- deploy/crds/openebs_v1alpha1_blockdevice_cr.yaml
- deploy/crds/openebs_v1alpha1_blockdeviceclaim_cr.yaml
- fixes a custom resource version error in sample yaml file
**Checklist:**
> fix(yaml): fix version of sample resources.

- deploy/helm/charts/Chart.yaml
- deploy/helm/charts/README.md
- deploy/helm/charts/templates/configmap.yaml
- deploy/helm/charts/values.yaml
- udpate README
- update values
- add os disk exclude path as a configuration
> [stable/ndm]: update charts to 1.4.0

- .github/workflows/build.yml
- .github/workflows/pull_request.yml
- .github/workflows/release.yml
- README.md
> chore(REAMDE): update project status

- .github/workflows/build.yml
- update build workflow conditions to ignore builds for release
> fix(workflow): update build workflow condition

- pkg/apis/openebs/v1alpha1/register.go
Signed-off-by: Sonia Singla <soniasingla.1812@gmail.com>
Bump deprecated logging package import :)
> Bump deprecated logging package import

- cmd/ndm_daemonset/app/command/device-list.go
- cmd/ndm_daemonset/probe/mountprobe_test.go
- db/kubernetes/client.go
- integration_tests/k8s/k8sclient.go
- integration_tests/k8s/k8sgen.go
- integration_tests/k8s/k8sndmresources.go
- pkg/controller/blockdevice/blockdevice_controller.go
- pkg/controller/blockdeviceclaim/blockdeviceclaim_controller.go
- pkg/smart/mockdata.go
Signed-off-by: Sahil Raja <sahil.raja@mayadata.io>
- Fixes opt.semgrep.err-nil-check warnings.
**Checklist:**
> (bugbash) Fix opt.semgrep.err-nil-check warnings

- integration_tests/k8s/k8sapi.go
- pkg/spdk/spdk.go
- pkg/sysfs/syspath.go
- pkg/util/strutil.go
- Fixes ST1019, SA6005, S1008 AND S1021 staticcheck warnings.
**Checklist:**
> (bugbash) Fix Staticcheck warnings

- cmd/manager/main.go
- cmd/ndm_daemonset/controller/controller.go
- cmd/ndm_daemonset/controller/sparsefilegenerator.go
- cmd/ndm_daemonset/grpc/api.go
- cmd/ndm_daemonset/probe/udevprobe.go
- pkg/logs/logs.go
- pkg/smart/satadevice.go
- pkg/smart/scsiinquirypage.go
Signed-off-by: Sahil Raja <sahil.raja@mayadata.io>
- Fixed unhandled errors.
- Fixed G104 gosec warnings. (BugBash)
**Checklist:**
> (bugbash) Fix G104 gosec warnings

- .github/workflows/build.yml
- .github/workflows/pull_request.yml
- .github/workflows/release.yml
- README.md
- cmd/manager/main.go
- cmd/ndm_daemonset/app/command/device-list.go
- cmd/ndm_daemonset/controller/controller.go
- cmd/ndm_daemonset/controller/sparsefilegenerator.go
- cmd/ndm_daemonset/grpc/api.go
- cmd/ndm_daemonset/probe/mountprobe_test.go
- cmd/ndm_daemonset/probe/udevprobe.go
- db/kubernetes/client.go
- integration_tests/k8s/k8sapi.go
- integration_tests/k8s/k8sclient.go
- integration_tests/k8s/k8sgen.go
- integration_tests/k8s/k8sndmresources.go
- pkg/apis/openebs/v1alpha1/register.go
- pkg/controller/blockdevice/blockdevice_controller.go
- pkg/controller/blockdeviceclaim/blockdeviceclaim_controller.go
- pkg/logs/logs.go
- pkg/smart/mockdata.go
- pkg/smart/satadevice.go
- pkg/smart/scsiinquirypage.go
- pkg/spdk/spdk.go
- pkg/sysfs/syspath.go
- pkg/util/strutil.go
Chery-pick PRs:
#570 
#571 
#572 
#573 
#568 
#566
> cherry-pick(bug, lint): fix lint and go errors from muse

- db/kubernetes/convert.go
- pkg/controller/blockdeviceclaim/blockdeviceclaim_controller.go
- pkg/upgrade/v040_041/preupgrade.go
- pkg/upgrade/v041_042/preupgrade.go
Signed-off-by: aSquare14 <atibhi.a@gmail.com>
Related to bugsbash
> (refactor, bugsbash) fixes implicit memory aliasing in for loop.

- integration_tests/k8s/k8sapi.go
Signed-off-by: aSquare14 <atibhi.a@gmail.com>
**Checklist:**
Where:
* `fix`         - for bug fixes or improvements, not a fix for build script
* `chore`       - changes not related to production code
* `docs`        - changes related …
> (refactor/bugsbash) remove unused var

- cmd/ndm_daemonset/probe/usedbyprobe.go
- integration_tests/utils/file.go
- pkg/sysfs/util.go
- pkg/udev/mockdata.go
Signed-off-by: aSquare14 <atibhi.a@gmail.com>
> (refactor, bugsbash) clean potential file inclusion via variable

- cmd/ndm_daemonset/probe/usedbyprobe.go
- db/kubernetes/convert.go
- integration_tests/k8s/k8sapi.go
- integration_tests/utils/file.go
- pkg/controller/blockdeviceclaim/blockdeviceclaim_controller.go
- pkg/sysfs/util.go
- pkg/udev/mockdata.go
- pkg/upgrade/v040_041/preupgrade.go
- pkg/upgrade/v041_042/preupgrade.go
List of PRs included:
- #576 
- #577 
- #578
> cherry-pick(bug, lint, sec): fix go lint and gosec errors

- pkg/smart/scsicommands.go
**Checklist:**
Where:
* `fix`         - for bug fixes or improvements, not a fix for build script
* `chore`       - changes not related to production code
* `docs`        - changes related to documentation
* `style`       - …
> add comment to fix linter

- deploy/helm/charts/Chart.yaml
- deploy/helm/charts/README.md
- deploy/helm/charts/values.yaml
> [stable/ndm]: update ndm to 1.4.1

- integration_tests/udev/disks.go
Signed-off-by: Pankaj Biradar <pankaj28988@gmail.com>
> Removed weak random number generator by adding new import

- pkg/mount/mountutil_test.go
> test(pkg, mount): Add tests for getPartitionName in TestGetMountAttr

- api-service/node/services/hugepages.go
**Checklist:**
Where:
* `fix`         - for bug fixes or improvements, not a fix for build script
* `chore`       - changes not related to production code
* `docs`        - changes related to documentation
* `style`       - …
> Fix Potential Integer overflow made by strconv.Atoi result conversion to int16/32

- pkg/udev/mockdata.go
Signed-off-by: Sonia Singla <soniasingla.1812@gmail.com>
Bugsbash
> Fix potential file inclusion via variable error

- deploy/helm/charts/Chart.yaml
- deploy/helm/charts/README.md
- deploy/helm/charts/values.yaml
> [stable/ndm]; update charts to 1.5.0

- cmd/manager/main.go
> fix(manager): set reconciliation interval for manager

- .github/workflows/chart-lint-test.yml
- deploy/helm/charts/Chart.yaml
- deploy/helm/charts/README.md
- deploy/helm/charts/crds/blockdevice.yaml
- deploy/helm/charts/crds/blockdeviceclaim.yaml
- deploy/helm/charts/templates/daemonset.yaml
- deploy/helm/charts/templates/deployment.yaml
- deploy/helm/charts/values.yaml
- update values
- update CRDs
- update daemonset with new feature gate
- update deployment with new readiness and liveness checks
> [stable/ndm]: update charts to 1.6.0

- BUILD.md
- README.md
- update readme with project roadmap and contributing guides
- add troubleshooting doc info
> doc(README): update roadmap and contributing guides

- deploy/ndm-operator.yaml
- deploy/yamls/ndm-cluster-exporter.yaml
- deploy/yamls/ndm-node-exporter.yaml
Exporter failed to start due to '==' typos in YAML file
Fix the typo
No
> fix(yaml): Fix '==' typo in exporter args

- .github/pull_request_template.md
- .github/workflows/build.yml
- .github/workflows/chart-lint-test.yml
- .github/workflows/pull_request.yml
- .github/workflows/release-charts.yml
- .github/workflows/release.yml
- CONTRIBUTING.md
- GOVERNANCE.md
- README.md
- RELEASE.md
- build/push
- code-standard.md
- git-workflow.md
- As part of inclusive naming, work towards renaming branches
with name master to develop
- add ghcr to supported registries
> chore(repo): rename master branch to develop

- cmd/ndm_daemonset/probe/addhandler.go
- cmd/ndm_daemonset/probe/blkidprobe.go
- cmd/ndm_daemonset/probe/eventhandler.go
- cmd/ndm_daemonset/probe/probe.go
- cmd/ndm_daemonset/probe/uuid.go
- cmd/ndm_daemonset/probe/uuid_test.go
- deploy/ndm-operator.yaml
- deploy/yamls/node-disk-manager.yaml
- pkg/blkid/blkid.go
- pkg/features/features.go
- pkg/partition/partition.go
**Why is this PR required? What issue does it fix?**: #621 
**What this PR does?**: Add partition table uuid support
**Does this PR require any upgrade changes?**: No
- on `CentOS 7` host: 🆗
- on `CentOS 8` host: 🆗
- on `Ubuntu 16.04` host: 🆗
**Checklist:**
> feat(uuid): add partition table uuid support
