- cmd/app/command/commands.go
- cmd/app/command/start.go
- cmd/controller/ctrl_main.go
This daemon will wait for SIGINT signal and if ctrl + c is pressed, the watcher will exit.
```
$ ndmctl -h
ndmctl controls the Node-Disk-Manager
Usage:
ndmctl [flags]
ndmctl [command]
Available Commands:
device      Operations on block devices
help        Help about any command
start       Node disk controller
Flags:
--alsologtostderr                  log to standard error as well as files
-h, --help                             help for ndmctl
--log-flush-frequency duration     Maximum number of seconds between log flushes (default 5s)
--log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
--log_dir string                   If non-empty, write log files in this directory
--logtostderr                      log to standard error instead of files …
```
> adding a dummy ndm controller.

- node-disk-manager.yaml
Fixes #7 
Made the following assumptions:
- A docker image will be available with latest tag at openebs/node-disk-manager:latest
- The ndm binary will be included in the docker image at /usr/sbin. 
- `ndm start` will start the node-disk-manager service. 
- Kubernetes Clusters will have the MountPropagation feature enabled
Tested in minikube using the following steps:
- Made docker image with `make`.
- Ran minikube with this command: `sudo minikube start --vm-driver=none --feature-gates=MountPropagation=true`
- In YAML changed value of `image` to match with newly built image and `imagePullPolicy` to `IfNotPresent`.
- Applied the YAML
- Checked pod description and log.
- Ran `lsblk` and `ndm` in both inside and outside the pod and match the results.
- Attached Pen Drive, then see if it is …
> Sample YAML for running node-disk-manager as k8s DaemonSet.

- .gitignore
- cmd/controller/ctrl.go
NDM is having separate logic to create UUID for the disk resources
which does not have the Wwn number. This patch will unify them
and have same kind of name for all kinds of disk resources.
```
$  kubectl get disks
NAME                                    AGE
disk-60118c2e5b9fe3c33884765ea95db585   7m
disk-dd038c382a92a22f75910b4198d18db2   3s
```
Earlier it was
```
$ kubectl get disk
NAME                                    AGE
disk-0x500003949d304e06                 45s
disk-b3f828db7cd829ac237e90ccf433bd17   5s
```
> unify disk resource name.

- cmd/controller/ctrl_main.go
- node-disk-manager.yaml
Pods will have hostname as pod name and some hash string
(e.g. node-disk-manager-29qw8) which changes with every pod
restart.
We are using system's hostname for populating the
disk resource in etcd. Disk resource should not use the hostname
of the pod for "kubernetes.io/hostname", it should be node's hostname,
which will tell us where the disk is attached to.
Here, we are passing the hostname as an environment to the Node-Disk-Manager
daemonset, which it will use to populate the disk resource in etcd.
> populating the hostnames correctly for the Disk resources.

- ndm-operator.yaml
- samples/node-disk-manager.yaml
It is cumbersome to apply more than one yamls to deploy a solution.
For NDM, we are applying crd yaml and deployment yaml for deployment.
Writing a complete yaml, which will do everyting like apply the
CRD yaml, create a service account, apply the deployment yaml would
be useful for users.
Signed-off-by: Pawan <pawanprakash101@gmail.com>
> creating a single yaml for the deployment of NDM

- ndm-operator.yaml
Fix NDM-operator `ClusterRole` rules and add `ServiceAccount` in daemonset deployment Spec.
Signed-off-by: prateekpandey14 <prateekpandey14@gmail.com>
> Fix ndm-operator ClusterRole rules

- Makefile
- README.md
- cmd/controller/controller.go
- cmd/controller/controller_test.go
- cmd/controller/diskstore.go
- cmd/controller/diskstore_test.go
- cmd/probe/eventhandler.go
- cmd/probe/eventhandler_test.go
- cmd/probe/udevprobe.go
- cmd/probe/udevprobe_test.go
- ndm-operator.yaml
- pkg/udev/common.go
- pkg/udev/common_test.go
- pkg/udev/device.go
- pkg/udev/device_test.go
- pkg/udev/enumerate.go
- pkg/udev/enumerate_test.go
- pkg/udev/listentry.go
- pkg/udev/mockdata.go
- pkg/udev/monitor.go
- pkg/udev/monitor_test.go
- pkg/udev/udev.go
- pkg/udevevent/event.go
- pkg/udevevent/event_test.go
- pkg/udevevent/monitor.go
- pkg/udevevent/monitor_test.go
- pkg/util/fdutil.go
- pkg/util/fdutil_test.go
- samples/node-disk-manager.yaml
Node-disk-manager will automate the management of the disk attached to the node. To automate management of disks node-disk-manager should be notified by udev-event module for two basic event disk attach and disk detach. Node-disk-manager will detect new disks attached to its node and create a Disk CR corresponding to the newly detected disk. In case this disk was moved from another node in the same cluster to this node, it should update the host-name associated with the disk.
libudev API calls will help to detect attach and detach event and get details info about attached or detached disk.
`Fig - flow of libudev API calls to monitor device.`
`Fig - udev-event module integration with node-disk manager.`
visual logs:
1. Pod log
```
shovan_maity@instance-1:~$ kubectl get pod
NAME …
```
> Udev-event module integration with node-disk-manager to automatically update disk cr

- cmd/app/command/device-list.go
- cmd/controller/controller.go
This PR removes ndm device list cli command output from pkg/controller. Now it prints using defaultDeviceList template.
* Previous output
```
root@instance-1:~#ndm device list
Path: /dev/sda
Size: 10737418240
Status: Active
Model: PersistentDisk
Serial: instance-1
Vendor: Google
Path: /dev/sdb
Size: 10737418240
Status: Active
Model: PersistentDisk
Serial: disk-1
Vendor: Google
```
* Current output
```
root@instance-1:~#ndm device list
NAME                                         MODEL               VENDOR              SERIAL                   STATUS    PATH      CAPACITY
disk-ccc636c88bd9ab09dde9de476309058d        PersistentDisk      Google              instance-1               Active    /dev/sda  10737418240
disk-ce41f8f5fa22acb79ec56292441dc207        PersistentDisk      Google …
```
> remove o/p dependency of ndm cli commands from pkg/controller

- cmd/controller/disk.go
- cmd/controller/disk_test.go
- cmd/controller/mockdata_test.go
- cmd/probe/eventhandler_test.go
- cmd/probe/udevprobe.go
- cmd/probe/udevprobe_test.go
- pkg/apis/openebs.io/v1alpha1/types.go
- pkg/udev/common.go
- pkg/udev/common_test.go
- pkg/udev/mockdata.go
For each disk by-id and by-path links are created using udev. These links are like -
```
/dev/disk/by-id/scsi-0Google_PersistentDisk_demo-disk
/dev/disk/by-path/virtio-pci-0000:00:03.0-scsi-0:0:4:0
```
these are added in Details of Disk cr's spec.
Describe disk -
```
shovan_maity@instance-1:~$ kubectl describe disk disk-ce41f8f5fa22acb79ec56292441dc207
Name:         disk-ce41f8f5fa22acb79ec56292441dc207
Namespace:    
Labels:       kubernetes.io/hostname=instance-1
Annotations:  <none>
API Version:  openebs.io/v1alpha1
Kind:         Disk
Metadata:
Cluster Name:        
Creation Timestamp:  2018-07-11T15:15:18Z
Generation:          0
Resource Version:    1076774
Self Link:           /apis/openebs.io/v1alpha1/disk-ce41f8f5fa22acb79ec56292441dc207
UID: …
```
> Add devlinks(by-id and by-path link) in disk cr 

- pkg/udev/common.go
by-id links were not in order in disk cr
This PR arrange them below order-
```
1. by-id link which contains serial no and bus
2. others links(if present)
```
DevLinks section of Disk CR
```
Devlinks:
Kind:  by-id
Links:
/dev/disk/by-id/scsi-0Google_PersistentDisk_ganesh-disk4
/dev/disk/by-id/google-ganesh-disk4
Kind:  by-path
Links:
/dev/disk/by-path/virtio-pci-0000:00:03.0-scsi-0:0:6:0
```
> Order by-id links in disk cr

- cmd/app/command/start.go
- cmd/controller/controller.go
- cmd/controller/controller_test.go
- cmd/controller/diskstore.go
- cmd/controller/diskstore_test.go
- cmd/controller/filter.go
- cmd/controller/filter_test.go
- cmd/controller/probe.go
- cmd/controller/probe_test.go
- cmd/filter/filter.go
- cmd/filter/filter_test.go
- cmd/filter/osdiskexludefilter.go
- cmd/filter/osdiskexludefilter_test.go
- cmd/probe/eventhandler.go
- cmd/probe/eventhandler_test.go
- cmd/probe/probe.go
- cmd/probe/probe_test.go
- cmd/probe/smartprobe.go
- cmd/probe/smartprobe_test.go
- cmd/probe/udevprobe.go
- cmd/probe/udevprobe_test.go
- ndm-operator.yaml
- pkg/util/mountutil.go
- pkg/util/mountutil_test.go
- samples/node-disk-manager.yaml
This PR contains plugable filter concept and os disk filter.
Filter interface is implemented in this PR.
In `Start()` of each filter we set range of check variables for that filter.
In `Include(*DiskInfo) bool` if property of disk matches with include value it returns true.
In `Exclude(*DiskInfo) bool` if property of disk does not match with exclude value it returns true.
If any of `Include()` or `Exclude()` returns true filter returns true.
**special notes for reviewer** -
I removed package level init for registering probes and filters. If I do like that then we will lost control of registering order as all of them are as go routine. And we want to register all filters then all probes so I have made separate register method of each probe and filters.
**Implementation steps** -
1. read …
> Filter os disk while creating/updating disk cr.

- cmd/controller/controller.go
- cmd/controller/disk.go
- cmd/controller/disk_test.go
- cmd/controller/diskstore_test.go
- cmd/controller/probe.go
- cmd/controller/probe_test.go
- cmd/controller/sparsefilegenerator.go
- cmd/controller/sparsefilegenerator_test.go
- cmd/probe/eventhandler_test.go
- cmd/probe/smartprobe_test.go
- cmd/probe/udevprobe_test.go
- ndm-operator.yaml
- pkg/util/sparsefile.go
- pkg/util/sparsefile_test.go
For testing with nodes that have no additional disks, sparse disks provide a
mechanism to create a sparse file and use as a disk resource.
The NDM sparse file creation can be configured via the following
environment variables:
- SPARSE_FILE_DIR : A valid directory where sparse files need to be created
- SPARSE_FILE_SIZE : Size of each sparse file in byte. Defaults to 1GB
- SPRASE_FILE_COUNT: Number of files to be created. Defaults to 1
To differentiate between sparse disks and regular disk, a disk-type label
as been introduced. For sparse disks, this disk-type will be `sparse`, where
as for regular disks it will be set as `disk`.
Like disk resources, the sparse disk resource's state will be marked as
`Uknown` when NDM is shutdown and is made `Active` when the NDM is restarted
on the same …
> Include support for creating sparse file

- pkg/udev/common.go
Virtuall disks generally have either all the disk
properties same (Model, serail, vendor, wwn) or the
propetties don't exits at all.
Here we are putting Hostname and devpath in the disk uid so
that NDM can differentiate the disk across the nodes and also
within the node.
After this change, we are able to see all the disks on the AWS cluster 
```
admin@ip-10-3-56-88:~/cstor_yaml$ kubectl get disks
NAME                                    AGE
disk-1d860ccc764933ec1200d5ed810b346b   1m
disk-79e82287d54cabca0a8e1d7abbed77eb   1m
disk-9636e82af96e4e681b2bb4c944c17fe7   1m
disk-9a8dfe972801dec81e7d31feb99c1f42   1m
disk-dc783fba0d1f3daf0ea0f3e9f4c45f50   1m
disk-dccd9baebf17a90f39e65859f3fadcbd   1m
```
```
admin@ip-10-3-40-249:~$ lsblk
NAME    MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
xvda    202:0 …
```
> NDM does not work well with the Virtual disks.

- cmd/filter/filter.go
- cmd/filter/pathfilter.go
- cmd/filter/pathfilter_test.go
- ndm-operator.yaml
- pkg/util/strmatch.go
- pkg/util/strmatch_test.go
- pkg/util/util.go
- pkg/util/util_test.go
Depending on where NDM is running - cloud or virtual hardware,
the host (udev) modules don't always provide all the required
details.
For instance, GKE nodes display loop back devices as disks,
where as disks in AWS don't always show typical device attributes
like - model, vendor or serial number.
This PR introduces a feature where, user can specify a list of
include/exclude keywords that can appear in the device path. For
exampke, the default configuration provided, excludes loop back
devices from being added as disks.
Signed-off-by: kmova <kiran.mova@openebs.io>
> feat(filters): include/exclude disks based on device path

- docs/developer-setup.md
Mention about the case when someone's GOPATH consists of more than one path in the `docs/developer-setup.md`
If above case holds true for anyone then he might get an error while running
some of the commands mentioned in this document. I think it is good to
at least mension about this case once in the document.
Changes committed:
modified:   docs/developer-setup.md
Signed-off-by: Abhishek Kashyap <abhishek.kashyap@mayadata.io>
> mention a special case related to `GOPATH` in `docs/developer-setup.md`

- pkg/udev/common.go
ndm is not able to generate uuid of virtual disks whose model is `Virtual_disk` this pr will add `Virtual_disk` model as a special case and allows ndm to generate uuid of that disk as the way it generates for `EphemeralDisk` model.
Changes committed:
modified:   pkg/udev/common.go
Signed-off-by: Shovan Maity <shovan.maity@mayadata.io>
> add support for virtual disk uuid generation

- cmd/controller/disk.go
- cmd/probe/smartprobe.go
- cmd/probe/smartprobe_test.go
- docs/design.md
- pkg/apis/openebs.io/v1alpha1/types.go
- pkg/server/server_test.go
- pkg/smart/doc.go
- pkg/smart/mockdata.go
- pkg/smart/scsidevice.go
- pkg/smart/scsiinquirypage.go
- pkg/smart/types.go
- samples/disk.yaml
This PR will introduce the following changes -
-  It will add logic to show the correct SPC version (i.e implemented specifications) of a disk instead of showing the raw version value obtained from scsi inquiry command.
-  It will change field **SPCVersion** to **Compliance** which seems to be a more generic term than SPCVersion.
- It will fix the nil pointer reference error in server_test file which occurs when the port to be checked is already on use and calling net.Listen returns error.
Changes committed:
modified:   cmd/controller/disk.go
modified:   cmd/probe/smartprobe.go
modified:   cmd/probe/smartprobe_test.go
modified:   docs/design.md
modified:   pkg/apis/openebs.io/v1alpha1/types.go
modified:   pkg/smart/doc.go
modified:   pkg/smart/mockdata.go
modified: …
> Add logic to show correct SPC version for disks rather than raw value

- pkg/smart/scsicommands.go
fix typo: occured -> occurred
Signed-off-by: vikash srivastava <srivastava.vikash@outlook.com>
fixes: #109
> Fix typo in scsicommand.go

- cmd/probe/eventhandler.go
After fixing mentioned lint error,
it throws following error 
`type name will be used as probe.ProbeEvent by other packages, and that stutters; consider calling this Event` [here](https://github.com/openebs/node-disk-manager/blob/master/cmd/probe/eventhandler.go#L33).
This error also came in other golang project, they solved it by changing the name. [Repo](https://github.com/giantswarm/inago/pull/43/files)
I have done what was asked in this issue. On your suggestion, I can work on the given lint error
g
> style(ndm): fixed eventhandler lint error

- pkg/apis/openebs.io/v1alpha1/types.go
- pkg/metrics/common.go
Fixes the linting in `metrics/common.go` file.
Signed-off-by: Richard Burk Orofeo chardy.orofeo@yahoo.com.ph
reference issue: #98
> style(ndm): Fixed `golint` error in pkg/metrics/common.go

- Gopkg.lock
- Gopkg.toml
- cmd/controller/ndmconfig.go
- cmd/controller/ndmconfig_test.go
- ndm-operator.yaml
- samples/node-disk-manager-config.yaml
Add yaml support for NDM config. json support is preserved.
Fixes #148
> Support yaml config for node-disk-manager

- pkg/smart/common.go
- pkg/smart/scsicommands.go
`readDeviceCapacity` used to send only a SCSI READ CAPACITY(10) command.
If this reports an overflow, issue an additional READ CAPACITY(16)
command to get the correct device capacity.
Signed-off-by: Michael Kaiser <patheticpat@googlemail.com>
> Fix readDeviceCapacity method (#147)

- pkg/udev/udev_test.go
Fixes #166
According to the Go Report Card for this project, there are two occurrences where the `err` variables are declared, but not used:
> Remove ineffectual assignments in udev_test.go

- .travis.yml
- Dockerfile.in
- entrypoint.sh
- hack/entrypoint.sh
- ndm-operator.yaml
Enable core dump in node-disk-manager.
Signed-off-by: satbir <satbir.chhikara@gmail.com>
> [Issue #179] Enable core dump in node-disk-manager

- Makefile
Remove extraneous lines following the "vet:" line.
Signed-off-by: Michael Breen <8309342+michael-db@users.noreply.github.com>
> fix broken Makefile rule "vet" to do "go vet" #182

- hack/build.sh
- hack/entrypoint.sh
Previously ndm process was main process of ndm pod (pid-1). Now ndm process is launched by `entrypoint.sh` for that 2 process are running inside ndm pod.
```
root@shovan-Latitude-3560:/# ps -aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0  18040  2756 ?        Ss   06:53   0:00 /bin/bash /usr/local/bin/entrypoint.sh
root         7  0.0  0.2 564108 21200 ?        Sl   06:53   0:00 /usr/sbin/ndm start
```
K8s sends `SIGKILL`, `SIGINT`, `SIGTERM` signals to main process (pid-1) and there were some cleanup process done by ndm when it gets `SIGKILL`, `SIGINT`, `SIGTERM` signals. NDM process was not getting these signals for this cleanup process stuck. Code in this pr caught `SIGINT` and `SIGTERM` signals and pass it to ndm process (chield …
> (fix): ndm cleanup process for graceful shutdown

- cmd/controller/controller.go
- cmd/controller/disk.go
- cmd/controller/disk_test.go
- cmd/controller/diskstore.go
- cmd/controller/diskstore_test.go
- cmd/probe/eventhandler_test.go
- cmd/probe/smartprobe_test.go
- cmd/probe/udevprobe_test.go
- disk.yaml
- samples/custom-disk.yaml
- samples/disk.yaml
If I create a custom disk using sample yaml ndm will make it's state inactive in every restart or if there is any error in ndm. This pr add one more label in disk cr to detect if the resource will be managed by
ndm or not.
NDM will manage those resources which contains `ndm.io/unmanage=false` in label.
To create a sable disk using spaese files or partition of a disk You need to modify (update disk/device attributes) and apply this [yaml](https://raw.githubusercontent.com/openebs/node-disk-manager/master/samples/disk.yaml) file.
Signed-off-by: Shovan Maity <shovan.cse91@gmail.com>
> (feat): add support for custom disk

- cmd/probe/seachestprobe.go
If NDM is run in unprivileged mode, Seachest probe was causing the pod into `CrashLoopBackOff` state. This was because Seachest was having insufficient permissions to fetch the details. The PR aborts filling the details by Seachest probe if its not able to get the `driveInfo` pointer.
> Error handling in seachest probe

- cmd/controller/disk.go
- cmd/probe/eventhandler.go
- cmd/probe/udevprobe.go
- cmd/probe/udevprobe_test.go
- pkg/apis/openebs.io/v1alpha1/types.go
- pkg/udev/common.go
- pkg/udev/common_test.go
- pkg/udev/mockdata.go
A new `PartitionInfo` struct is introduced in `DiskInfo` to store details of partitions in the disk. This partition data will be added to the Disk CR in etcd which can be used for further purposes like filtering.
This PR is the first step towards solving the filtering of LVM/partititons as mentioned in #74
> Fill filesystem and partition info into Disk CR

- ndm-operator.yaml
- samples/node-disk-manager.yaml
Changed `ImagePullPolicy` to `IfNotPresent`. Earlier, during integration testing the old image from docker-hub was pulled which overwrite the newly built images. This resulted in integration tests being performed on the old image and also the old image was retagged and pushed. With the change, only the newly built image will be used.
The update strategy of Daemonset is now set to RollingUpdate, so that the new image will be applied without manual deletion.
> fix (yaml): changed pull policy and upgrade strategy

- .travis.yml
Operator-sdk work on go version "1.10.3" or later. This PR is to make NDM use "1.10.3" go version.
Signed-off-by: satbir <satbir.singh@mayadata.io>
> [US4256] feat(operator-sdk): Changing go version to work with operator-sdk

- cmd/probe/udevprobe.go
Removes a hardcoded log message which caused an index out of bound
error while performing the initial scan on udev
> fix (udev) : index out of bound error while scanning partitions

- .travis.yml
- cmd/controller/sparsefilegenerator.go
when sparsefile size is specified in exponential notation from platform like rancher, ndm could not parse it. Now this parsing is enabled by first parsing the string to float64 and then converting to int64
> fix (sparsefile): parse file-size in non-int format

- build/ndm-daemonset/entrypoint.sh
When `env GOTRACE` was used, the ndm daemon set was not receiving the environment variable. Now we `export` the variable so that it is set in the environment where ndm daemon-set binary is run.
> fix(script): Enabling core dump for ndm daemon-set

- hack/entrypoint.sh
when `env GOTRACE` was used, the ndm daemon set was not receiving the environment variable. Now we export the variable so that it is set in the environment where ndm daemon-set binary is run.
cherry-pick #219
> fix(script): Enabling core dump for ndm daemon-set (cherry-pick #219)

- cmd/ndm_daemonset/probe/udevprobe.go
- cmd/ndm_daemonset/probe/udevprobe_test.go
- pkg/udev/device.go
- pkg/udev/monitor_test.go
- pkg/udev/udev_test.go
If `libudev` returns an invalid address/nil pointer while trying to create a udev struct from syspath, the error was not checked or logged. 
This PR enables logging and  error checking,  and aborts fetching details using udev probe if libudev returns nil.
> fix(udev): added nil check while getting udev devices

- cmd/probe/udevprobe.go
- cmd/probe/udevprobe_test.go
- pkg/udev/device.go
- pkg/udev/monitor_test.go
- pkg/udev/udev_test.go
When libudev return an invalid address/ nil pointer, the error was not logged and handled. Enabled logging and error handling for this case.
cherry-pick #230
> fix(udev) : added udev nil check (cherry-pick #230)

- cmd/ndm_daemonset/controller/sparsefilegenerator.go
- cmd/ndm_daemonset/controller/sparsefilegenerator_test.go
When sparse file size is specified in exponential notation from platform like rancher and pharos, ndm could not parse it. Now this parsing is enabled by first parsing the string to float64 and then converting to int64
> fix (sparsefile): parse file size in non-int format

- build/ndm-daemonset/entrypoint.sh
- ndm-operator.yaml
changed the hostpath at which sparse file is created by NDM. Now sparse file will be created at `/var/openebs/sparse` directory. Also, the core-dump will be stored at the same location.
> fix(yaml): changed host path for creating sparse file

- hack/entrypoint.sh
- ndm-operator.yaml
changed the hostpath at which sparse file is created by NDM. Now sparse file will be created at `/var/openebs/sparse`. Also, the core-dump will be stored at the same location.
cherry-pick #232
> fix(yaml): changed host path for creating sparse file (cherry-pick #232)

- cmd/ndm_daemonset/controller/controller.go
- cmd/ndm_daemonset/controller/devicestore.go
- cmd/ndm_daemonset/controller/diskstore.go
runtime client is now created using client.New() instead of from the manager. update on the disk/device CR now takes the latest resource version and updates the resource
> fix(controller): fixed client init and CR update

- ndm-operator.yaml
sparse file will be now created in `/var/openebs/sparse`, instead of `/var/openebs`.
> fix(yaml): change directory to create sparse file

- cmd/ndm_daemonset/filter/osdiskexcludefilter.go
- ndm-operator.yaml
`/proc/1/mounts` cannot be mounted into container in systems with selinux enabled. But `/proc` directory can be mounted. This fix mounts the `/proc` directory to `/host/proc` inside container and thus the mounts file will be available at `/host/proc/1/mounts`.
> fix(code,yaml): fix to mount the /proc directory of host

- .travis.yml
changes to push node-disk-operator images to docker hub and quay
> fix(travis): push node-disk-operator image

- cmd/ndm_daemonset/controller/blockdevicestore.go
- cmd/ndm_daemonset/controller/diskstore.go
- cmd/ndm_daemonset/controller/sparsefilegenerator.go
- cmd/ndm_daemonset/controller/sparsefilegenerator_test.go
- pkg/controller/blockdevice/blockdevice_controller.go
Sparse disk is refactored  to block device resource. Only block device resources will be created for sparse files. These block devices of type sparse can be used for creating sparse pool.
Fixes https://github.com/openebs/node-disk-manager/issues/250
> refactor(disk): Refactor sparse disk to sparse block device

- cmd/ndm_daemonset/controller/blockdevice.go
- cmd/ndm_daemonset/controller/controller.go
- cmd/ndm_daemonset/controller/controller_test.go
- deploy/crds/openebs_v1alpha1_disk_crd.yaml
- ndm-operator.yaml
- pkg/controller/blockdevice/blockdevice_controller.go
Change BlockDevice and BlockDeviceClaims apis to namespace scoped. Corresponding changes are done in controller logic which creates BD, and also in reconcilation loop of BlockDevice
> fix(apis): change BD and BDC to namespace scoped

- cmd/ndm_daemonset/probe/eventhandler.go
- cmd/ndm_daemonset/probe/eventhandler_test.go
- cmd/ndm_daemonset/probe/udevprobe.go
BlockDevice will get deactivated when the corresponding device is removed from the host.
Fixes #255 
> fix(blockdevice): deactivate block device when Device is removed

- cmd/ndm_daemonset/controller/controller.go
Runtime client does not detect CRDs that are installed after the client is instantiated. Therefore we create the client everytime while searching for CRDs. If CRD is available we go with the latest generated client.
> fix(controller): generate client while searching for CRD

- cmd/ndm_daemonset/controller/disk_to_device_converter_test.go
- cmd/ndm_daemonset/controller/disk_to_device_convertor.go
- cmd/ndm_daemonset/probe/eventhandler.go
- cmd/ndm_daemonset/probe/eventhandler_test.go
The UUID used earlier was of the format 'disk-xxx', this need to be changed to `blockdevice-xxx`
> fix(eventhandler): fix blockdevice not getting deactivated

- pkg/controller/blockdeviceclaim/blockdeviceclaim_controller.go
- pkg/controller/blockdeviceclaim/blockdeviceclaim_controller_test.go
Earlier, BDC was deleted by NDM-Operator, if the claim had an invalid capacity field. Now the BDC won't be deleted and its status/phase will be updated as `Invalid Capacity Requested`.
> fix(controller): remove BDC deletion

- cmd/ndm_daemonset/controller/blockdevicestore.go
Fixes an issue where ClaimRef and ClaimState were being blanked out after a block device is detached and attached to a node.
Steps to reproduce: 
1. A disk is attached to the node. NDM daemon detects it and creates a block device resource with status as active
2. A BDC is created which claims this BD. When the BD is claimed , claimRef field is added and claimState is changed to Claimed in the BD by the NDM operator.
3. The disk is now removed from the node. The disk status will be updated as Inactive by the Daemonset.
4. The disk is reattached . DS fetches all the details of the disk, and update this information into the BD. At this point the claimRef and claimState that was updated by the operator is lost.
The fix will update the claimRef and claimState values from old CR to the new CR. …
> fix(event-handler): fix ClaimRef missing when updating Block Devices.

- integration_tests/sanity/deviceclaim_test.go
- ndm-operator.yaml
- pkg/apis/openebs/v1alpha1/blockdevice_types.go
- pkg/cleaner/cleaner.go
- pkg/cleaner/config.go
- pkg/cleaner/jobcontroller.go
- pkg/controller/blockdevice/blockdevice_controller.go
- pkg/controller/blockdeviceclaim/blockdeviceclaim_controller.go
When a BDC was deleted, the BD was unclaimed and could be claimed by other BDCs. In this case the data on the BD remains. This PR introduces a scrub job which will delete the data on the BD. 
The new workflow will be like: When a BDC is deleted, the BD will be marked as `Released`. The reconcile loop will pick up all BDs in released state and creates a scrub job for those BDs. If a job is already in progress, then new job will not be created.
The job can perform 2 opertions depending on the BD: 
1. If the BD is used as a raw block device, a `dd` command will be issued on the BD to wipe out all the data. This takes significantly long duration.
2. If the BD is used as a volume i.e it was preformatted and mounted before claiming, then an `rm -rf` will be issued by the job. Only the data will …
> feat(scrub-job): scrub job to clean data on released block devices

- cmd/ndm_daemonset/controller/blockdevice.go
- cmd/ndm_daemonset/controller/blockdevicestore.go
- cmd/ndm_daemonset/controller/blockdevicestore_test.go
- pkg/controller/blockdevice/blockdevice_controller.go
- pkg/controller/blockdevice/blockdevice_controller_test.go
Add `ndm.io/managed` labels for BlockDevices, similar to disk. BlockDevices which are not managed by NDM will not be made active/inactive by the DaemonSet. Also, unmanaged blockdevices are ignored by the operator to check whether the block devices have a backing disk or not.
> feat(blockdevice): add support for managed=false on BlockDevices

- cmd/ndm_daemonset/probe/mountprobe.go
kubelet mount points are excluded by mount probe. If mount probe detects a kubelet mountpoint for a disk, the mount info and file system info is skipped from being added into the custom resources.
> fix(probe): exclude kubelet mountpoints from mount-probe

- ndm-operator.yaml
- pkg/cleaner/config.go
- pkg/cleaner/jobcontroller.go
Fixed high cpu/io utilization of cleanup job. Using `dd` caused heavy load on the CPU, and prevented other pods from getting scheduled on the node. It also caused kube-api server crash at times. By using `wipefs` instead of `dd` only the file-system signatures will be erased. This process is much faster than writing zeros, since we are only working with certain block(superblocks).
> fix(cleaner): change dd to wipefs

- pkg/seachest/seachest.go
Seachest probe was holding onto file descriptors for LVM devices. This was because, we were not issuing a close() call to the device struct(which inturn closes the FD to `/dev/dm-`). `close_Device()` will close the open file descriptor to the device.
Fixes https://github.com/openebs/openebs/issues/2655
> fix(seachest,probe): fix seachest keeping open FDs

- .travis.yml
- pkg/seachest/seachest.go
use latest seachest release for building NDM. The `Release-19.06` fixes stack corruption issue and initial code for support for NVMe devices.
> fix(seachest, travis): use latest release of seachest  

- ndm-operator.yaml
- pkg/setup/create_crd.go
This PR handles the upgrade scenarios of CRDs (disk, bd and bdc). When a new change is seen in the CRD object, operator will create a json patch and update the CRD object with the patch.
> fix(operator, upgrade): handle CRD upgrade from operator

- .travis.yml
upgrade seachest version to `Release-19.06.02`. This fixes issue of seachest crashing with NVMe devices, in which write cache is supported.
> fix(travis): upgrade seachest version

- Makefile
- cmd/manager/main.go
- integration_tests/k8s/k8sapi.go
- integration_tests/k8s/k8sndmresources.go
- integration_tests/sanity/deviceclaim_test.go
- integration_tests/sanity/upgrade_test.go
- pkg/upgrade/preupgrade.go
- pkg/upgrade/preupgrade/preupgrade.go
- pkg/upgrade/upgrade.go
This PR adds a new pkg to perform upgrade operations. Preupgrade -> upgrade -> postupgrade tasks all can be performed using the package. It is also possible to handle upgrade for multiple release versions.
Currently, only the preupgrade script is being executed. It handles renaming finalizer in BDC.
> feat(upgrade): perform upgrade from NDM operator

- pkg/controller/blockdeviceclaim/blockdeviceclaim_controller.go
since BDC can have multiple finalizers, there will be cases where BDC is scheduled for deletion, but not cleared from etcd due to finalizers. Such BDCs should not be processed and BD should not be claimed for those BDCs.
> fix(controller): claim BD only if BDC is not scheduled for deletion

- cmd/ndm_daemonset/controller/controller.go
- cmd/ndm_daemonset/controller/controller_test.go
- integration_tests/yamls/clusterrole.yaml
- ndm-operator.yaml
earlier node name was used as `kubernetes.io/hostname`, in disk and blockdevices. But in some cloud providers like AWS, node name and hostname are not same. Therefore, now we fetch the nodename using downward API, and then get the hostname label set on that node.
> fix(daemon, controller): change nodeName to hostname in disk and BD

- ndm-operator.yaml
- pkg/cleaner/cleaner.go
- pkg/cleaner/config.go
- pkg/cleaner/jobcontroller.go
add service account to cleanup jobs, so that job pods requiring privileged access can be started in openshift cluster.
Fixes [openebs#2698](https://github.com/openebs/openebs/issues/2698)
> fix(cleaner): add service account to cleanup job

- docs/cleanup-design.md
- integration_tests/sanity/customresources_test.go
- integration_tests/sanity/k8s_tests.go
- pkg/apis/openebs/v1alpha1/blockdevice_types.go
- pkg/apis/openebs/v1alpha1/disk_types.go
- pkg/cleaner/cleaner.go
- pkg/cleaner/jobcontroller.go
- pkg/controller/blockdevice/blockdevice_controller.go
This fix makes sure that cleanup jobs are started only on Active BDs. Also, if the BD goes into another state, during cleanup, the job will be cancelled and BD state will remain unchanged. This ensures that stale jobs are not present in the cluster, when corresponding BDs have been removed.
> fix(cleaner): cancel jobs of inactive blockdevices

- cmd/ndm_daemonset/controller/blockdevice.go
- cmd/ndm_daemonset/controller/blockdevicestore.go
- cmd/ndm_daemonset/controller/blockdevicestore_test.go
- cmd/ndm_daemonset/controller/controller.go
- cmd/ndm_daemonset/controller/disk.go
- cmd/ndm_daemonset/controller/disk_test.go
- cmd/ndm_daemonset/controller/disk_to_device_convertor.go
- cmd/ndm_daemonset/controller/diskstore.go
- cmd/ndm_daemonset/controller/diskstore_test.go
- cmd/ndm_daemonset/controller/probe.go
- cmd/ndm_daemonset/controller/sparsefilegenerator.go
- cmd/ndm_daemonset/controller/sparsefilegenerator_test.go
- cmd/ndm_daemonset/probe/eventhandler_test.go
- cmd/ndm_daemonset/probe/seachestprobe.go
- cmd/ndm_daemonset/probe/smartprobe_test.go
- cmd/ndm_daemonset/probe/udevprobe_test.go
- deploy/crds/openebs_v1alpha1_blockdevice_cr.yaml
- pkg/apis/openebs/v1alpha1/blockdevice_types.go
- pkg/cleaner/jobcontroller.go
- pkg/controller/blockdevice/blockdevice_controller_test.go
- pkg/controller/blockdeviceclaim/blockdeviceclaim_controller.go
- pkg/controller/blockdeviceclaim/blockdeviceclaim_controller_test.go
- pkg/controller/disk/disk_controller_test.go
Currently only hostname was included as part of the device information. This has been refactored to include nodename and hostname along with provision for multiple other fields which can be used for geolocating a node and its associated disks and BDs.
**Note for Reviewer**: Most of the test cases in daemonset controller and probes has been refactored in this PR with labelling changes.
> feat(apis, controller, manager): include node attributes to disk/BD

- deploy/crds/openebs_v1alpha1_blockdeviceclaim_cr.yaml
- pkg/apis/openebs/v1alpha1/blockdeviceclaim_types.go
- pkg/controller/blockdeviceclaim/blockdeviceclaim_controller.go
- pkg/select/blockdevice/filters.go
- pkg/select/blockdevice/select.go
Added node name filter to BDC.
Use case:
1. If hostname is only given, matching BDs on the host will be used for selection
2. If nodename is only given, matching BDs on the node will be used for selection
3. If both hostname and nodename are provided, BDs with matching hostname and nodename will be used for selection
4. If no node selection value is provided, all BDs will be used for selection
> feat(apis, selector): add node name filter

- pkg/setup/build_crd.go
add node name to printer column of BlockDevice CRD. This will result in `kubectl get bd` also list the name of the node to which the BD is attached
```
user@host:/$ kubectl get bd
NAME                                           NODENAME                                   SIZE           CLAIMSTATE   STATUS   AGE
blockdevice-4833f3d01155d26a61cb0a92e6b122fc   gke-akhil-ndm-default-pool-b62186cd-85fn   402653184000   Unclaimed    Active   30m
sparse-b60e173560072794680c46d75b33490b        gke-akhil-ndm-default-pool-b62186cd-85fn   1073741824     Unclaimed    Active   30m
```
> fix(installer): add node name to printer column of CRD

- cmd/ndm_daemonset/filter/osdiskexcludefilter.go
- cmd/ndm_daemonset/filter/osdiskexcludefilter_test.go
If `os-disk-filter` failed to find the device in which os is installed, the os-filter should not match with any devices. But currently if the filter failed to initialize, all devices on that node were getting excluded. A change has been introduced in the regex to fix this bug. 
Related Issues: [#2727](https://github.com/openebs/openebs/issues/2727)
> fix(filter): fix os-filter to ignore empty exclude paths

- pkg/upgrade/upgrade.go
- pkg/upgrade/v040_041/preupgrade.go
- pkg/upgrade/v041_042/preupgrade.go
This PR removes duplicated code in upgrade pkg. The interface definition for upgrade task has been changed so that only required functions need to be written, reducing the amount of boilerplate
> refactor(upgrade): remove duplicated code in upgrade

- docs/developer-setup.md
The `developer-setup` doc has been updated with steps to setup `openSeachest` for compiling ndm. Also new steps for running integration tests are updated.
> docs: update docs with latest setup guide

- .travis.yml
- Makefile
- README.md
- build/build.sh
Related to:
- https://github.com/openebs/openebs/issues/1295
- https://github.com/openebs/node-disk-manager/pull/306
This PR refactors the build scripts ( .travis.yaml and Makefile) to allow
for compiling on different platforms like `amd64` and `arm64` without 
having to make changes to the build scripts. 
The following changes have been made: 
- `shellcheck` is triggered as a seperate step from .travis.yaml, as it is only available for amd64
- updated the Makefile to initialize ARCH and BASEIMAGE depending on the platform where builds are initiated. 
- updated the build to make use of gox to allow for cross compilation
- made some cosmetic changes to Makefile for better readability. 
- updated the README with dependency on SeaChest libraries. 
Attempted to automate the building of arm64 …
> refactor(build): for multiple arch compilation using gox

- Makefile
With this change, user can specify a custom
base OS image for arm64 binaries using the ENV
variable `BASE_DOCKER_IMAGEARM64`.
The default base image will be `arm64v8/ubuntu:18.04`
Signed-off-by: kmova <kiran.mova@mayadata.io>
> feat(build): make the base-os for arm images configurable

- pkg/mount/mountutil.go
- pkg/mount/mountutil_test.go
nvme devices has a different syspath since it belongs to a different subsystem. Thus the nvme instance name need to be searched instead of the `block` keyword. This will help identify the parent disk.
> fix(mount): fix parent disk detection for nvme devices.

- pkg/udev/common.go
This PR aims to resolve #188 for KVM-based virtualization, while awaiting global changes on disk detection strategy (https://github.com/openebs/openebs/pull/2666)
Signed-off-by: Aurelien Guillaume <aurelien@iwi.me>
> Fixes device detection for KVM-based virtualization

- pkg/udev/common.go
cherry-pick #333 for fixing disk identification issues on KVM host.
Signed-off-by: Aurelien Guillaume <aurelien@iwi.me>
> cherry-pick(333) : Fixes device detection for KVM-based virtualization

- cmd/ndm_daemonset/controller/blockdevicestore.go
- cmd/ndm_daemonset/controller/diskstore.go
moved to klog
The purpose of this change is to help with generating alerts based on the log messages from all openebs components through elasticsearch and elastalert. It is easy to parse the logs and generate alerts if the log messages are all formatted in a predefined way.
Signed-off-by: moteesh <moteesh@gmail.com>
> logs formatted for easy parsing for sending alerts based on logs

- build/build.sh
- cmd/manager/main.go
- cmd/ndm-exporter/cmd/root.go
- cmd/ndm_daemonset/app/command/commands.go
- ndm-exporter/exporter.go
- pkg/version/version.go
`Version` and `GitCommit` is now added as part of NDM build. This will enable the binaries to log commit from which the build was generated and also the version of NDM. 
By default `ci` will be the version used. For releases and RC builds the tags will be used as version.
> feat(build, version): add version and commit to builds

- blockdevice/blockdevice.go
- cmd/ndm-exporter/cmd/root.go
- db/kubernetes/client.go
- db/kubernetes/client_test.go
- db/kubernetes/convert.go
- db/kubernetes/convert_test.go
- db/kubernetes/fake_test.go
- db/kubernetes/filter.go
- db/kubernetes/filter_test.go
- ndm-exporter/collector/static.go
- ndm-exporter/exporter.go
- pkg/metrics/static/metrics.go
refactor the kubernetes client code:
- add functions to convert from k8s API to core BlockDevice struct
- add methods to generate filter specific to kubernetes
- make namespace a part of the k8s client
> refact(client): refact kubernetes client 

- ndm-operator.yaml
- pkg/cleaner/config.go
The default helper pod which can be overridden via the
ENV was set to fixed older version. This can result in
default image to have some security vulnerabilities.
As part of the release process, the helper pod images will
be rebuilt allowing to pull in a image that has fixed
known security vulnerabilities.
Signed-off-by: kmova <kiran.mova@mayadata.io>
> fix(tools): set the default tag to latest for helper pod

- ndm-operator.yaml
- pkg/cleaner/config.go
The default helper pod which can be overridden via the
CLEANUP_JOB_IMAGE environment variable was set
to fixed older version. This can result in default image
to have some security vulnerabilities.
As part of the release process, the helper pod images will
be rebuilt allowing to pull in a image that has fixed
known security vulnerabilities.
Signed-off-by: kmova <kiran.mova@mayadata.io>
(cherry picked from commit 56a2deb43eff0361e40d885e6f208341b6b34afd)
> fix(tools): set the default tag to latest for helper pod (#351)

- cmd/ndm_daemonset/probe/udevprobe.go
- pkg/hierarchy/device.go
- pkg/udev/common.go
All the dependent devices of the discovered blockdevice will be logged during the initial udev scan. This will help to get an idea of the disk level hierarchy on the nodes. This will also make it easier to debug on systems without always needing the output of `lsblk`.
The generated logs will be like:
```
I1129 12:21:32.043470       6 udevprobe.go:220] starting udev probe listener
I1129 12:21:32.044252       6 udevprobe.go:157] Dependents of /dev/sda : {Parent: Partitions:[/dev/sda1 /dev/sda14 /dev/sda15] Holders:[] Slaves:[]}
I1129 12:21:32.044774       6 udevprobe.go:157] Dependents of /dev/sda1 : {Parent:/dev/sda Partitions:[] Holders:[] Slaves:[]}
I1129 12:21:32.045274       6 udevprobe.go:157] Dependents of /dev/sda14 : {Parent:/dev/sda Partitions:[] Holders:[] Slaves:[]}
I1129 …
```
> chore(hierarchy, udev): add disk level hierarchy logs 

- cmd/ndm_daemonset/controller/blockdevicestore.go
- cmd/ndm_daemonset/controller/controller.go
- cmd/ndm_daemonset/controller/diskstore.go
- pkg/controller/blockdevice/blockdevice_controller.go
- pkg/controller/blockdeviceclaim/blockdeviceclaim_controller.go
- pkg/controller/disk/disk_controller.go
`openebs.io/reconcile: "false"` annotation can be set on BlockDevice, Disk and BlockDeviceClaim custom resources to stop reconciliation of those resources.
Disabling reconciliation is useful while handling upgrades. No updates will be done on the Disk, BDs, BDCs etc if the reconciliation is disabled. This means that both the NDM operator and the NDM daemon will not be updating the Disk and BlockDevice resource when the reconcile annotation is set.
> feat(reconcile, controller): disable reconciliation on custom resources

- cmd/ndm_daemonset/controller/blockdevicestore.go
- cmd/ndm_daemonset/controller/controller.go
- cmd/ndm_daemonset/controller/diskstore.go
- pkg/controller/blockdevice/blockdevice_controller.go
- pkg/controller/blockdeviceclaim/blockdeviceclaim_controller.go
- pkg/controller/disk/disk_controller.go
`openebs.io/reconcile: "false"` annotation can be set on BlockDevice, Disk and BlockDeviceClaim custom resources to stop reconcilation of those resources.
add functionality to disable reconcilation from daemon also. When the annotation is specified, the daemon also will not update the details into the disk and blockdevice resource.
> chore(cherry-pick): disable reconciliation on custom resources (#307)

- build/ndm-daemonset/entrypoint.sh
Earlier NDM used to rewrite the system core pattern so that the core
dump is available in the persistent `/var/openebs/sparse` directory.
But this will cause all process on the host to write core files to that directory.
Now NDM process will be launched from the openebs directory, so core
files will get automatically written to the `$PWD`. This will help to
remove changing the system core pattern.
> fix(script): fix changing the system core pattern

- cmd/ndm_daemonset/app/command/commands.go
- cmd/ndm_daemonset/app/command/device-list.go
- cmd/ndm_daemonset/app/command/start.go
- cmd/ndm_daemonset/controller/controller.go
- cmd/ndm_daemonset/controller/ndmconfig.go
- cmd/ndm_daemonset/controller/ndmconfig_test.go
The config file path was hardcoded to `/host/node-disk-manager.config`. This is now made configurable and can be provided via `--config`. This will help to run the NDM daemon as a standalone binary without needing to be in a container. When in the container the config file will be provided via a `ConfigMap`.
> feat(daemon): make config file path configurable

- blockdevice/blockdevice.go
- db/kubernetes/convert.go
- db/kubernetes/convert_test.go
- ndm-exporter/collector/seachest.go
- ndm-exporter/collector/static.go
- ndm-exporter/exporter.go
- ndm-operator.yaml
- pkg/metrics/seachest/metrics.go
- pkg/metrics/smart/metrics.go
- added node level exporter for fetching metrics using seachest library. 
- In this PR, only the current temperature info of the disk is exposed as metrics. More metrics like disk rotation rate can be fetched from seachest library. 
- More collectors can be added by following steps in #347 .
>  feat(exporter): add collector for fetching metrics using seachest library

- build/ndm-daemonset/entrypoint.sh
- ndm-operator.yaml
disable coredump from NDM daemon by default. `ENABLE_COREDUMP` env needs to be used to enable core dump. When core dump is enabled, the ulimit will be set to unlimited and a core directory will be created inside `SPARSE_FILE_DIR` to store the core files.
> fix(script): disable coredump in NDM daemon

- build/ndm-daemonset/entrypoint.sh
- ndm-operator.yaml
disable coredump from NDM daemon by default. `ENABLE_COREDUMP` env needs to be used to enable core dump. When core dump is enabled, the ulimit will be set to unlimited and a core directory will be created inside `SPARSE_FILE_DIR` to store the core files.
cherry-pick  : 1c5a67115d6f034b28ab557f0bdb69768c1074d8, ff7c7e97495b1be20d1b38364ffacd36ce3e0203
> chore(cherry-pick): disable core dump by default

- pkg/cleaner/cleaner.go
- pkg/cleaner/jobcontroller.go
- Added function to get Node Object using Cleaner Operator
- Added function to get Tolerations from the Node Taints
- Added one more parameter in NewCleanupJob to set Tolerations of Job to be created.
Signed-off-by: Rahul M Chheda <rahul.chheda@mayadata.io>
Logs: These are sequential logs, will the steps I performed:
```
rahul_chheda_mayadata_io@rahulchheda:~/openebs$ kubectl get pods -n openebs
NAME                                           READY   STATUS    RESTARTS   AGE
maya-apiserver-5865d7d548-bmzck                1/1     Running   0          2d
openebs-admission-server-684d455954-zvgrv      1/1     Running   0          2d
openebs-localpv-provisioner-58f5df5458-ttmw8   1/1     Running   0          2d
openebs-ndm-8c4cs                              1/1     Running   0          21s …
```
> fix(cleanup) : Fixed creation of cleanUp Job

- pkg/cleaner/cleaner.go
- pkg/cleaner/jobcontroller.go
Cleanup pods will be now launched with tolerations for the nodes in which the released 
blockdevice is present. This will prevent jobs from being stuck in Pending state, and 
blockDevices stuck in Released state when one or more nodes on the cluster are tainted.
- Added function to get Node Object using Cleaner Operator
- Added function to get Tolerations from the Node Taints
- Added one more parameter in NewCleanupJob to set Tolerations of Job to be created.
This is cherry-pick from commit: https://github.com/openebs/node-disk-manager/commit/a6eb990b582f4c537844c5d9d5fa1e933d31e817
Signed-off-by: Rahul M Chheda <rahul.chheda@mayadata.io>
> fix(cleanup) : Fixed creation of cleanUp Job (#363)

- pkg/crds/build.go
- pkg/setup/build_crd.go
**Why we need this?**
This commit will add the support for display `PATH` of `BlockDevice`
- The `PATH` will only be displayed when `-o wide` flag is passed
Issue Fixed: https://github.com/openebs/openebs/issues/2836
Outputs:
```
$ kubectl get bd 
NAME                                           NODENAME           SIZE          CLAIMSTATE   STATUS   AGE
blockdevice-b8c766547ce524dd9cf53ef003d54558   node-dev-setup03   5368709120    Unclaimed    Active   21m
sparse-01e10418d6b3ff0e5955046bd36b0f79        node-dev-setup02   10737418240   Unclaimed    Active   21m
sparse-5698d9c1a580e6af110a8359fa292926        node-dev-setup01   10737418240   Unclaimed    Active   21m
sparse-d1806a93ae6ecc94cebe50a225dc1cc5        node-dev-setup03   10737418240   Unclaimed    Active   21m
```
```
$ kubectl get …
```
> chore(bd): Add support for display PATH in kubectl output

- build/ndm-daemonset/entrypoint.sh
- ndm-operator.yaml
OpenEBS basepath has been added. Each component of openebs will have a directory under OPENEBS_IO_BASE_DIR on the host machine. 
NDM components will be stored under `OPENEBS_IO_BASE_DIR/ndm` on the host. Inside the NDM container this path will be mapped to `/var/openebs/ndm`.
> feat(script, yaml): add openebs basepath

- build/ndm-daemonset/entrypoint.sh
- ndm-operator.yaml
Make the location for saving the NDM cores inline with other openebs components by providing the location where core's should be saved. 
The default location is /var/openebs/ndm, which can be changed by passing the right value in the deployment file.
cherry-pick : 692804837755a2166353a19c95b7f799eb24c6ea
> feat(script, yaml): customize the location for ndm cores (#362)

- .travis.yml
- Makefile
- build/install-dep.sh
- build/install-test-infra.sh
- build/integration-test.sh
- build/test.sh
- auto build and push `arm64` and `amd64` binaries
- make tests dependent on the platform
shellcheck, unit-tests and integration tests will be run only on `amd64`, along with the build. On all other platforms the binary will be built and image will be pushed.
> feat(build): enable auto build for arm64 binaries

- .travis.yml
This PR adds ppc64le to travis builds.
> Adding ppc64le build

- build/ndm-daemonset/Dockerfile.in
- build/ndm-daemonset/entrypoint.sh
- cmd/ndm_daemonset/app/command/commands.go
- cmd/ndm_daemonset/controller/controller.go
- cmd/ndm_daemonset/controller/ndmconfig.go
- integration_tests/yamls/daemonset.yaml
- ndm-operator.yaml
- pkg/features/features.go
- pkg/features/features_test.go
- pkg/features/util.go
added support for feature gates. The features to be enabled or disabled can be specified via the command line arguments in the operator-yaml.
example:
```
serviceAccountName: openebs-ndm-operator
containers:
- name: node-disk-manager
image: akhilerm/node-disk-manager-amd64:ci
args:
- -v=4
- --feature-gates="GPTBasedUUID"
imagePullPolicy: Always
securityContext:
privileged: true
```
The above will enable the UUID feature on the NDM daemon.
If NDM is used as a standalone binary instead of the operator-yaml/docker image, then the feature flags are enabled by `--feature-gates="Feature1,Feature2,Feature3"`
> feat(config): add support for feature gates.

- .travis.yml
- Makefile
- build/install-dep.sh
- build/install-test-infra.sh
- build/integration-test.sh
- build/test.sh
refactor build script and ci scripts to work on multiple platforms. Only on amd64, the unit tests and integration tests will be run. On all other platforms, the binary and docker images will be built
and pushed.
> cherry-pick(build): enable auto build for arm64 binaries (#371)

- blockdevice/blockdevice.go
- cmd/ndm_daemonset/probe/udevprobe.go
- cmd/ndm_daemonset/probe/udevprobe_test.go
- pkg/udev/common.go
- pkg/udev/common_test.go
- pkg/udev/mockdata.go
- pkg/udevevent/event.go
- pkg/udevevent/event_test.go
- added PartitionInfo struct which contains information if the given blockdevice is a partition. The information includes, partition number, parition UUID, partition table UUID and partition table type.
- added FileSystemUUID which will store the UUID of the filesystem, if a filesystem exists on the blockdevice
- fetch partition number, partition table (UUID/type), partition UUID from udev
- fetch partition number, partition table (UUID/type), partition UUID from udev
- fill all details required for creating UUID during udev event, instead of relying on additional probe. This will help to generate UUID even if all the probe fails.
> feat(core, udev): add partition related information to blockdevice

- cmd/ndm_daemonset/probe/seachestprobe.go
Attributes that are guaranteed to be filled by other probes are removed from seachest. 
seachest-probe will be used to fetch details that are exclusively given by seachest library.
Note: seachest can't be used to fill in storage/capacity related fields,
because the library will always report the capacity/blocksize of the main
disk even if the query is made for the partition. This will result in wrong
information being filled in the blockdevice resource. The sysfs probe will be
used to get all capacity related information from the sysfs filesystem
The following fields which are removed will be filled using:
Controller : Hostname
UdevProbe : DevPath, Model, WWN, Serial, Vendor
SysfsProbe : Storage, DriveType
Some fields like RotationRate, Endurance etc has been removed as they are still not …
> refact(seachest,probe): remove unused attributes from seachest probe

- pkg/apis/openebs/v1alpha1/blockdevice_types.go
add new fields into `spec.details` of blockdevice API
- logicalBlockSize
- physicalBlockSize
- hardwareSectorSize
- driveType
> feat(apis): add block size and drive type fields

- cmd/ndm_daemonset/controller/blockdevice.go
- cmd/ndm_daemonset/controller/disk_to_device_convertor.go
- cmd/ndm_daemonset/probe/eventhandler_test.go
- cmd/ndm_daemonset/probe/seachestprobe.go
- cmd/ndm_daemonset/probe/smartprobe_test.go
- cmd/ndm_daemonset/probe/sysfsprobe.go
- cmd/ndm_daemonset/probe/udevprobe_test.go
Fill the following details into the BD resource:
- drive type, logical/physical block size, hw sector size
The above details will be fetched by sysfs probe and then filled into the block device resource
> refact(core, api): fill block sizes in blockdevice resource

- pkg/apis/openebs/v1alpha1/blockdevice_types.go
add logical/physical block size, hardware sector size and drive type fields into the blockdevice spec.details
cherry-pick : #388 
> cherry-pick(apis): add block size and drive type fields

- cmd/ndm_daemonset/controller/blockdevicestore.go
- cmd/ndm_daemonset/controller/blockdevicestore_test.go
- cmd/ndm_daemonset/probe/eventhandler.go
This PR fix metadata part of a block device. Now users can label and annotate block devices. What it does it actually takes metadata of older block device and patch that with system generated information.
Signed-off-by: Shovan Maity <shovan.maity@mayadata.io>
> fix(block-device): allow client to label and annotate bd

- cmd/ndm_daemonset/controller/blockdevicestore.go
- cmd/ndm_daemonset/controller/blockdevicestore_test.go
- cmd/ndm_daemonset/probe/eventhandler.go
labels and annotations added by user on block device resource will be persisted on BlockDevice resource
**Notes for Reviewer:**
Some changes has been made in [eventhandler.go](https://github.com/openebs/node-disk-manager/pull/398/files#diff-ae2e61e489512702afed7a256852a54b) which vary from the original commit, because of backporting changes.
> cherry-pick(core, label): persist label and annotation on BD

- pkg/apis/openebs/v1alpha1/blockdeviceclaim_types.go
- pkg/controller/blockdeviceclaim/blockdeviceclaim_controller.go
- pkg/controller/blockdeviceclaim/blockdeviceclaim_controller_test.go
- pkg/select/blockdevice/filters.go
- add `metav1.LabelSelector` to BlockDeviceClaim spec
- updated list method from BDC controller to handle custom label selector.
> feat(controller, api): add label selector to BlockDeviceClaim

- pkg/apis/openebs/v1alpha1/blockdeviceclaim_types.go
- pkg/controller/blockdeviceclaim/blockdeviceclaim_controller.go
- pkg/controller/blockdeviceclaim/blockdeviceclaim_controller_test.go
- add label selector to BDC api.
- add label selector to list method using labels.Selector
- include hostname label in the metav1.LabelSelector from BlockDeviceClaim
- add test cases for selector in BDC
cherry-pick #397
> cherry-pick(controller, api): add label selector to BlockDeviceClaim (#397)

- db/kubernetes/client.go
- db/kubernetes/filter.go
- pkg/controller/blockdeviceclaim/blockdeviceclaim_controller.go
- pkg/select/blockdevice/filters.go
- pkg/select/blockdevice/filters_test.go
- pkg/select/blockdevice/select.go
- add support for new label `openebs.io/block-device-tag`
- add a new filter while claiming block devices. If `openebs.io/block-device-tag` is present on a BlockDevice, only BDCs having a matching selector will be able to claim that block device
- fix a bug where selector is accidentally updated on BDC while updating other fields.
Sample BDC Yaml which makes use of `openebs.io/block-device-tag` label
```yaml
apiVersion: openebs.io/v1alpha1
kind: BlockDeviceClaim
metadata:
finalizers:
- openebs.io/bdc-protection
name: bdc-ss35
namespace: default
spec:
blockDeviceName: blockdevice-91d422d8517f935431daae722f8fdfa0
resources:
requests:
storage: 10M
selector:
matchLabels:
openebs.io/block-device-tag: X
status:
phase: Bound
```
BlockDevice that was claimed by the above BDC
```yaml
kind: …
```
> feat(controller,filter): add blockdevice tag label while claiming

- cmd/ndm_daemonset/controller/controller.go
- pkg/controller/blockdeviceclaim/blockdeviceclaim_controller.go
- pkg/select/blockdevice/filters.go
- pkg/select/blockdevice/filters_test.go
- pkg/select/blockdevice/select.go
- add support for new label `openebs.io/block-device-tag`
- add a new filter while claiming block devices. If `openebs.io/block-device-tag` is present on a BlockDevice, only BDCs having a matching selector will be able to claim that block device
- Fix a bug where selector is accidentally updated on BDC while updating other fields.
BDC controller used a pointer reference of the selector. This
has been changed to copy the selector and use it. This is done so that
an update on the BDC object does not cause the selector to get
updated with a different value other than the one which was applied by
user.
- Add unit tests for new filter
Sample BDC Yaml which makes use of `openebs.io/block-device-tag` label
```yaml
apiVersion: openebs.io/v1alpha1
kind: BlockDeviceClaim
metadata:
finalizers:
- …
```
> cherry-pick(controller,filter): add blockdevice tag label while claiming (#400)

- pkg/partition/partition.go
- pkg/partition/partition_test.go
add pkg to create partitions. The partition pkg is a wrapper over go-diskfs. Currently methods are added to create a single partition on the disk. Only GPT based partitions will be created on the disk.
> feat(partition): add pkg to create partitions

- changelogs/unreleased/409_akhilerm
- cmd/ndm_daemonset/filter/vendorfilter.go
- cmd/ndm_daemonset/filter/vendorfilter_test.go
This PR adds `OpenEBS` to the list of default excluded vendors. This is done so that, even if user removes the vendor filter, OpenEBS created iscsi disks are excluded by NDM.
- add OpenEBS as a default vendor in vendor filter
- modify test cases to add OpenEBS as a default vendor
No
None
**Checklist:**
> fix(filter): add default vendor OpenEBS in vendor filter

- build/custom-boilerplate.go.txt
- changelogs/unreleased/410_akhilerm
- cmd/ndm_daemonset/filter/devicevalidityfilter.go
- cmd/ndm_daemonset/filter/devicevalidityfilter_test.go
- cmd/ndm_daemonset/filter/filter.go
Fixes: [#3020](https://github.com/openebs/openebs/issues/3020).
This PR prevents NDM from creating BlockDevice resource for invalid disk events (events that are generated due to iscsi login issues). Thus, large no.of resources without any identity will not be created.
- add new DeviceValidityFilter to check if the device has valid fields
- dev path and capacity will be currently validated
- add unit test cases for the new filter
No
_Mention if this PR is part of any design or …
> feat(filter): add new filter to validate block devices

- .gitignore
- Makefile
- build/ndm-daemonset/Dockerfile.in
- build/ndm-exporter/Dockerfile.in
- build/ndm-operator/Dockerfile.in
- build/push
There are cases where users might want to build and push
container images in their own environments.
This commit will help customizing docker images via environment variables:
- The following ENV help specify custom docker build args
- DBUILD_SITE_URL ( default: https://openebs.io )
- DBUILD_REPO_URL ( default: https://github.com/openebs/node-disk-manager )
- The following ENV allows Travis to specify custom image org
- IMAGE_ORG (default: openebs )
- The following ENV will allow specifying an extra tag suffix
- TAG_SUFFIX ( default: none )
No. 
Used make file commands to create …
> refact(build): make the docker images configurable

- blockdevice/blockdevice.go
- changelogs/unreleased/386_akhilerm
- cmd/ndm_daemonset/app/command/device-list.go
- cmd/ndm_daemonset/controller/blockdevicestore.go
- cmd/ndm_daemonset/controller/blockdevicestore_test.go
- cmd/ndm_daemonset/controller/controller.go
- cmd/ndm_daemonset/controller/probe.go
- cmd/ndm_daemonset/controller/probe_test.go
- cmd/ndm_daemonset/probe/eventhandler.go
- cmd/ndm_daemonset/probe/eventhandler_test.go
- cmd/ndm_daemonset/probe/smartprobe_test.go
- cmd/ndm_daemonset/probe/udevprobe.go
- ndm-operator.yaml
- pkg/hierarchy/device.go
- pkg/partition/partition_test.go
- pkg/udev/common.go
- pkg/udev/mockdata.go
- pkg/udevevent/event.go
- pkg/udevevent/event_test.go
- pkg/udevevent/monitor.go
This PR fixes the issue of disk unique identification in NDM. It implements the algorithm mentioned in [OEP#2666](https://github.com/openebs/openebs/pull/2666). This will make NDM uniquely identify disks without an identifier in a cluster. Disk movement from one node to another, creating block device resources for partitions is also supported.
- add support for partitions in NDM
- implement the new UUID algorithm mentioned in [#2666](https://github.com/openebs/openebs/pull/2666)
- changes made on the a claimed BlockDevice (like creating partitions) are ignored.
- if partitions are created on an unclaimed device, the device is marked inactive and resources will be created for the partitions.
**Does this PR …
> feat(partition, uuid): add partition support and UUID implementation

- Makefile
- cmd/ndm_daemonset/filter/devicevalidityfilter_test.go
- db/kubernetes/client_test.go
- pkg/features/features.go
- pkg/features/features_test.go
- pkg/features/util.go
- pkg/hierarchy/syspath_test.go
- pkg/select/blockdevice/filters_test.go
This PR contains changes to ensure that all files have a license header. License header checking was disabled in the Makefile. It is now enabled
- add missing license header to files
- make license check mandatory during build
No
- try to build while a file does not have license header fails
This was enabled/mandatory initially. But in some previous PR, the check was disabled because the target was changed. 
**Checklist:**
> chore(build): make license check mandatory during build

- changelogs/unreleased/416_akhilerm
- pkg/controller/blockdevice/blockdevice_controller.go
- pkg/controller/blockdeviceclaim/blockdeviceclaim_controller.go
- pkg/controller/util/finalizer.go
When a user deletes a BD that is claimed, the BD will be automatically recreated by NDM daemon pod. But the recreated BD will be in Unclaimed state. Thus another claim can get bound to the same BD resulting in data corruption.
- add `openebs.io/bd-protection` finalizer to BDs that are in `Claimed` state
No
- claimed a BD, try to delete the BD, the delete should not happen. the BD should get deleted only after it is Unclaimed. (after cleanup)
- old BDs already in claimed state should get this finalizer on the first reconciliation …
> fix(controller): add finalizer to claimed BD

- cmd/ndm_daemonset/probe/eventhandler.go
- cmd/ndm_daemonset/probe/udevprobe.go
- pkg/udevevent/event.go
- pkg/udevevent/event_test.go
Some storage arrays give LUNs having same WWN,  but with different serial number. We need to uniquely identify those LUNs. Therefore, if WWN is present a combination of WWN and Serial will be used.
- add Serial number to UUID generation algorithm
- fix test case using Serial  number along with WWN
Yes. Upgrade changes will be same as that of #386 
Continuation of #386 
**Checklist:**
> fix(uuid): add serial number to UUID algorithm

- build/push
This PR removes the leading `v` from image tags. This is required to make the image name
consistent with other openebs images 
- remove the leading `v` prefix from image tag
No
**Checklist:**
> refactor(build): trim leading v from image tag

- cmd/421_akhilerm
- cmd/manager/main.go
- pkg/env/env.go
- pkg/env/env_test.go
When helm install for openebs was introduced, there was no way for helm to install CRDs. So both maya api-server and NDM had code to install the respective CRDs as part of initialization.
With Helm 3, the CRDs can be installed via helm. There have been some requests for moving the CRD installations outside of the code for cases where Kubernetes installers like Lokomotive and others, would like granular control on how the required objects are installed.
- add `OPENEBS_IO_CRD_INSTALL` environment variable to enable / disable
installation of BlockDevice and BlockDeviceClaim CRDs
No
**If the changes in this PR are …
> feat(install, crd): add env to enable/disable CRD installation

- cmd/421_akhilerm
- cmd/manager/main.go
- pkg/env/env.go
- pkg/env/env_test.go
When helm install for openebs was introduced, there was no way for helm to install CRDs. So both maya api-server and NDM had code to install the respective CRDs as part of initialization.
With Helm 3, the CRDs can be installed via helm. There have been some requests for moving the CRD installations outside of the code for cases where Kubernetes installers like Lokomotive and others, would like granular control on how the required objects are installed.
- add OPENEBS_IO_CRD_INSTALL environment variable to enable / disable
installation of BlockDevice and BlockDeviceClaim CRDs
No
**If the changes in this PR are …
> cherry-pick(install, crd): add env to enable/disable CRD installation

- cmd/manager/main.go
- pkg/controller/blockdevice/blockdevice_controller.go
- pkg/controller/blockdeviceclaim/blockdeviceclaim_controller.go
- pkg/logs/logs.go
When using controller runtime logs, the logs contained information even from vendored packages with the complete stack rather than the point of error. This was making it difficult for debugging and also flooded the logs.
```
{"level":"info","ts":1588942250.7956839,"logger":"controller_deviceclaim","msg":"BlockDeviceClaim State is:Pending","Request.Namespace":"default","Request.Name":"bdc-ssa"}
{"level":"error","ts":1588942250.7958782,"logger":"controller_deviceclaim","msg":"Error selecting device","Request.Namespace":"default","Request.Name":"bdc-ssa","error":"no devices found matching the criteria","stacktrace":"github.com/openebs/node-disk-manager/vendor/github.com/go-logr/zapr.(*za …
```
> refactor(operator): add klog into NDM operator

- changelogs/unreleased/426-akhilerm
- cmd/ndm_daemonset/app/command/commands.go
- cmd/ndm_daemonset/controller/controller.go
- cmd/ndm_daemonset/probe/eventhandler.go
- cmd/ndm_daemonset/probe/udevprobe.go
- pkg/features/features.go
- pkg/features/features_test.go
The feature gate used to be a part of the daemon controller. This restricted its use to only code paths which had access to the controller pointer. This PR removes the dependency of feature gates on the daemon controller and can be used globally across the code base.
- adds a new exporter variable `FeatureGates` in features package which holds the state of all features.
- remove feature gate from daemon controller
No
- tested by providing a set of correct and incorrect feature gates.
**Any additional information for your …
> fix(featuregate): make feature gate independent of controller

- Makefile
shellcheck url has been changed and its breaking the build with the following error:
```
You are downloading ShellCheck from an outdated URL!
Please update to the new URL:
https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.x86_64.tar.xz
For more information, see:
https://github.com/koalaman/shellcheck/issues/1871
PS: Sorry for breaking your build :(
```
The url is now updated to point to the github repository
No
_Mention if this PR is part …
> chore(Makefile): update shellcheck url

- Makefile
shellcheck url has been changed and its breaking the build with the following error:
```
You are downloading ShellCheck from an outdated URL!
Please update to the new URL:
https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.x86_64.tar.xz
For more information, see:
https://github.com/koalaman/shellcheck/issues/1871
PS: Sorry for breaking your build :(
```
The url is now updated to point to the github repository
No
cherry pick #431 …
> cherry-pick(Makefile): update shellcheck url

- changelogs/unreleased/443-akhilerm
- pkg/apis/openebs/v1alpha1/blockdeviceclaim_types.go
- pkg/controller/blockdeviceclaim/blockdeviceclaim_controller.go
- pkg/controller/blockdeviceclaim/blockdeviceclaim_controller_test.go
The `InvalidCapacityRequest` phase was a wrong addititon into `status.phase` of BlockDeviceClaim. But invalid capacity can only be a reason for the BDC to remain in Pending state. This also guarantees that, even if invalid capacity is given after editing the capacity to a correct value, the BDC can get Bound.
Deprecate the `InvalidCapacityRequest` phase from block device claim. The phase will be moved to Pending and invalid capacity can only be a reason for BDC remaining in Pending state. Exisiting BDCs with the phase will be changed to Pending.
No
**If the changes in this PR are manually verified, list down the …
> fix(api, controller): deprecate invalid capacity request

- Makefile.buildx.mk
builds from travis were using the image name without `arch`  suffix.
renamed variable for image name, used in multiarch builds so that images
with ARCH suffix are generated from travis.
No
- Tested that both multiarch and arch dependent images can be built using the same makefile.
A minor fix for the mulitiarch changes in #428 
**Checklist:**
> chore(build): fix image name in non multiarch builds

- changelogs/unreleased/445-akhilerm
- pkg/cleaner/jobcontroller.go
When an application creates partitions on a claimed disk, currently only the partition table is wiped as part of
cleanup. There are chances that filesystem can exist on the partitions.  In such a scenario, creating another partition
starting at the same sector as the earlier one, causes system picking up the filesystem signature from the
previous partition and using it.
To fix the above issue, first the filesystem signature in the partitions need to be wiped and then the partition table. 
This PR modifies the `wipefs` command to list all the partitions of the claimed disk and wipe each one of them, starting with the FS signature in the partitions. Also …
> fix(cleaner); fix cleaning partitions before wiping main disk

- .travis.yml
since multi-arch images are now built for NDM, travis builds for arm64 and ppc64le will be disabled. 
remove `arm64` and `ppc64le` from travis builds
No
Continuation of https://github.com/openebs/node-disk-manager/pull/428
**Checklist:**
> chore(build): disable arm and ppc64le builds in travis

- .github/workflows/pull_request.yml
- Makefile.buildx.mk
Currently, multiarch images are built only after merging the changes to master. This PR adds a workflow to build the multiarch image for pull requests.
- Adds option to specify operation for mulitarch image result (push, load, cache)
1. Push: the mulitarch image will be pushed to the image registry
2. Load: the image will be loaded to local docker (image will be built only for the platform of build machine)
3. Cache: Image will be available only in the build cache
- refactor platform names
No
Yes, built and loaded single platform image using buildx
**Any additional information for …
> chore(build): refactor buildx script and add ci builds

- changelogs/unreleased/445-akhilerm
- pkg/cleaner/jobcontroller.go
When an application creates partitions on a claimed disk, currently only the partition table is wiped as part of
cleanup. There are chances that filesystem can exist on the partitions. In such a scenario, creating another partition
starting at the same sector as the earlier one, causes system picking up the filesystem signature from the
previous partition and using it.
To fix the above issue, first the filesystem signature in the partitions need to be wiped and then the partition table.
This PR modifies the wipefs command to list all the partitions of the claimed disk and wipe each one of them, starting with the FS signature in the partitions. Also partprobe …
> cherry-pick(cleaner); fix cleaning partitions before wiping main disk (#445)

- changelogs/unreleased/450-akhilerm
- cmd/ndm_daemonset/probe/usedbyprobe.go
NDM was keeping a file descriptor open after an exclusive open, causing other applications to receive a resource busy error.
Closes the open FD
fixes https://github.com/openebs/openebs/issues/3079
No
Bug was introduced in used-by probe as part of https://github.com/openebs/node-disk-manager/pull/430
**Checklist:**
> fix(probe): close open fd after exclusive open

- changelogs/unreleased/450-akhilerm
- cmd/ndm_daemonset/probe/usedbyprobe.go
NDM was keeping a file descriptor open after an exclusive open, 
causing other applications to receive a resource busy error.
Closes the open FD
Cherry-pick #450 
**Checklist:**
> cherry-pick(probe): close open fd after exclusive open (#450)

- changelogs/unreleased/455-harshthakur9030
- cmd/ndm_daemonset/probe/eventhandler.go
- cmd/ndm_daemonset/probe/udevprobe.go
- go.mod
- go.sum
This PR exposes the method which is used to sync etcd and ndm local state
Exposes rescan method which helps to sync etcd and ndm local state. It also ensures that the udev method being called is thread safe. 
No
Tested it on a GKE cluster.  
This is required for the gRPC PR.
**Checklist:**
> refactor(code): Exported rescan functionality

- Makefile
- build/build.sh
- changelogs/unreleased/456-harshthakur9030
Removes gox and builds using native go compiler
Replaces gox and builds multi-arch binaries with native go compiler
No
Verified that the multi-arch images are built successfully.
**Checklist:**
> chore(dependency): Remove gox as a dependency

- changelogs/unreleased/459-harshthakur9030
- go.mod
- vendor/golang.org/x/sync/AUTHORS
- vendor/golang.org/x/sync/CONTRIBUTORS
- vendor/golang.org/x/sync/LICENSE
- vendor/golang.org/x/sync/PATENTS
- vendor/golang.org/x/sync/semaphore/semaphore.go
- vendor/modules.txt
This PR upgrades to go version to 1.14
It makes the CI and the repo's go version consistent with each other.
Yes, go version is upgraded
Manually built the binary locally
Should be merged after removing gox PR as the go.mod file doesn't contain gox as a dependency anymore. 
https://github.com/openebs/node-disk-manager/pull/456
**Checklist:**
> feat(dependency): Upgrade go version to 1.14

- .github/workflows/build.yml
- .github/workflows/pull_request.yml
- .github/workflows/release.yml
- .travis.yml
As part of migrating from travis to github actions, unit tests need to be added in github actions workflow.
- add unit tests to github actions along with support to upload coverage report
to codecov. unit-tests are added to build and pull request workflows.
- remove uploading coverage report from travis
- print BRANCH and TAG envs in build and release workflow
No
Yes. Checked in local fork with tests and coverage result upload
unit-tests are not added to release workflow. This …
> test(unit-tests, coverage): add unit tests to github actions workflow

- changelogs/unreleased/463-akhilerm
- pkg/cleaner/jobcontroller.go
After cleaning up the device, partprobe was run on the device to reload the changes into the kernel. But running partprobe on sparse blockdevices can error out. 
-  Added an additional check to run `partprobe` only if the device is a block file.
No
Yes. The following 2 cases were tested.
1. Run the cleanup job on a sparse file
2. Run the cleanup job on a regular disk
Fix bug introduced in  #445 …
> fix(cleanup): run partprobe commands only on block files

- .github/workflows/build.yml
- build/push
- changelogs/unreleased/467-akhilerm
Currently the ci images from release branches are having a prefix `v`, eg: `v0.7.x-ci`. But to make naming consistent across all the images we need to use only `0.7.x-ci`. 
This PR removes the prefix from both the push script as well as the multiarch image.
No
This PR is part of [#137](https://github.com/openebs/charts/pull/137) to remove `v` prefix from all image tags.
**Checklist:**
> chore(build): fix build and push script to remove `v` prefix

- cmd/ndm_daemonset/app/command/start.go
- cmd/ndm_daemonset/grpc/api.go
- integration_tests/sanity/grpc_tests.go
- ndm-operator.yaml
Port of the API service was hardcoded to a common port and as NDM uses host network, it could cause a conflict with other apps running on that port. 
Makes the ip address and port configurable and changes the default port to 9115.
No
Checked with passing the new flag and without. 
#433 
**Checklist:**
> fix(address): Make api service address configurable

- pkg/cleaner/jobcontroller.go
cleanup job fails on partitions, because the partprobe command fails with invalid argument error.
Fix the cleanup script to run partprobe only on blockdevices having deviceType as disk
No
- claimed a sparse blockdevice, unclaimed and wiped it 
- claimed a whole disk for cstor, unclaimed and wiped it
- claimed a single partition for cstor, unclaimed and cleaned it up.
- claimed an LVM device for cstor, unclaimed and wiped it.
Continuation of #463 …
> fix(cleanup): fix cleanup job to run partprobe command only on disk types.

- changelogs/unreleased/473-akhilerm
- cmd/manager/main.go
- cmd/ndm_daemonset/controller/controller.go
NDM was crashing on systems were port 8080 is already in use. NDM daemonset uses the host network and if the port 8080 on host machine is being used, NDM crashed. This was because controller-runtime by default tries to start a server at port 8080 as part of initialization, and if it fails, the initialization errors out.
Disables the default metrics server in daemonset and operator.
No
Run the NDM daemonset on a machine were port 8080 was already in use and no crashes were observed.
**Any additional information for your …
> fix(manager): disable metrics server from controller runtime

- changelogs/unreleased/473-akhilerm
- cmd/manager/main.go
- cmd/ndm_daemonset/controller/controller.go
NDM was crashing on systems were port 8080 is already in use. NDM daemonset uses the host network and if the port 8080 on host machine is being used, NDM crashed. This was because controller-runtime by default tries to start a server at port 8080 as part of initialization, and if it fails, the initialization errors out.
Disables the default metrics server in daemonset and operator.
cherry-pick #473 
**Checklist:**
> cherry-pick(manager): disable metrics server in controller runtime

- .travis.yml
- Makefile.buildx.mk
- build/ndm-daemonset/Dockerfile
- build/ndm-exporter/Dockerfile
- build/ndm-operator/Dockerfile
- changelogs/unreleased/476-akhilerm
CVE-2020-16845 has been reported for go versions earlier to 1.14.7, this PR upgrades the go version for both travis builds and
multiarch builds to use go 1.14.7
- move build files to separate directory
- update go version to 1.14.7
No
Built the binary
**Checklist:**
> refact(build): update go version to 1.14.7

- blockdevice/blockdevice.go
- changelogs/unreleased/475-akhilerm
- cmd/ndm_daemonset/controller/blockdevice.go
- cmd/ndm_daemonset/controller/disk_to_device_convertor.go
- cmd/ndm_daemonset/controller/ndmconfig.go
- cmd/ndm_daemonset/probe/customtagprobe.go
- cmd/ndm_daemonset/probe/customtagprobe_test.go
- cmd/ndm_daemonset/probe/mountprobe.go
- cmd/ndm_daemonset/probe/probe.go
`openebs.io/block-device-tag` label can be used on the blockdevice resources to reserve devices to some application. Earlier this label need to added manually to each blockdevice by the user. In this PR, this step is automated. User can specify a regex pattern and all device path which match this path will be added the user provided label
NOTE: Currently only device path based matching is supported
Adds a new probe called `customTagProbe` which can be used to add labels to blockdevices based on the user provided configuration. Following is a sample config
```
tagConfigs:
- name: "Cassandra Device"
type: path
pattern: "/dev/sdc"
tag: "cassandra"
```
No
**If the …
> feat(probe, config): add support for config based tag on blockdevices

- .github/workflows/build.yml
- .github/workflows/pull_request.yml
Currently license check is done as part of the build process, after installing dependencies. Adding this check to lint job saves time by failing the build earlier if the licenses are not up-to-date
- add license check as part of lint job so that the build can fail fast, if license fails. 
No
**Checklist:**
> chore(build): add license check as part of lint job

- changelogs/unreleased/479-akhilerm
- pkg/controller/blockdeviceclaim/blockdeviceclaim_controller.go
When a Claimed BD is manually deleted by removing the finalizer, and later when the user
tries to delete BDC, NDM operator will continuously crash. This because NDM operator
tries to release a non existent BD.
adds a check to throw an error when the claimed BD is not found. This PR also adds an event to BDC when BlockDevice is not found.
No
**Checklist:**
> fix(controller): fix nil pointer dereference in BDC controller due to non existent BD

- .travis.yml
- Makefile.buildx.mk
- build/ndm-daemonset/Dockerfile
- build/ndm-exporter/Dockerfile
- build/ndm-operator/Dockerfile
- changelogs/unreleased/476-akhilerm
- move build files to separate directory
- update go version to 1.14.7 due to vulnerability in earlier versions (CVE-2020-16845)
cherry-pick #476 
> cherry-pick(build): update go version to 1.14.7 (#476)

- changelogs/unreleased/479-akhilerm
- pkg/controller/blockdeviceclaim/blockdeviceclaim_controller.go
when a Claimed BD is manually deleted by removing the finalizer, and later when the user
tries to delete BDC, NDM operator will continuously crash. This because NDM operator
tries to release a non existent BD. This change throws an error and add an event to BDC
when a corresponding BD cannot be found.
cherry-pick #479 
> cherry-pick(controller): fix nil pointer dereference in BDC controller due to non existent BD

- blockdevice/blockdevice.go
- changelogs/unreleased/475-akhilerm
- cmd/ndm_daemonset/controller/blockdevice.go
- cmd/ndm_daemonset/controller/disk_to_device_convertor.go
- cmd/ndm_daemonset/controller/ndmconfig.go
- cmd/ndm_daemonset/probe/customtagprobe.go
- cmd/ndm_daemonset/probe/customtagprobe_test.go
- cmd/ndm_daemonset/probe/mountprobe.go
- cmd/ndm_daemonset/probe/probe.go
`openebs.io/block-device-tag` label can be used on the blockdevice resources to reserve devices to some application. Earlier this label need to added manually to each blockdevice by the user. In this PR, this step is automated. User can specify a regex pattern and all device path which match this path will be added the user provided label
NOTE: Currently only device path based matching is supported
Adds a new probe called `customTagProbe` which can be used to add labels to blockdevices based on the user provided configuration. Following is a sample config
```
tagConfigs:
- name: "Cassandra Device"
type: path
pattern: "/dev/sdc"
tag: "cassandra"
```
cherry-pick #475 
> cherry-pick(probe, config): add support for config based tag on blockdevices

- changelogs/unreleased/404-akhilerm
- pkg/select/blockdevice/select.go
Enforce check on block device tag even for cases where block 
devices are claimed with block device name. 
cherry-pick #404 
> cherry-pick(filter): add `block-device-tag` filter during manual claiming (#404)

- blockdevice/blockdevice.go
- cmd/ndm_daemonset/probe/seachestprobe.go
- ndm-exporter/collector/seachest.go
- pkg/metrics/smart/metrics.go
- pkg/seachest/seachest.go
Exports seachest data which is already fetched
Exports seachest data to prometheus
No
The following data is exported :
HighestTemperature
LowestTempearature
RotationalLatency
Capacity
LogicalSectorSize
PhysicalSectorSize
RotationRate
DriveType
TotalBytesRead
TotalBytesWritten
DeviceUtilization
Other than the above, Rotational Latency is calculated and exported
**Checklist:**
> feat(metrics): exporting seachest data to prometheus

- changelogs/unreleased/492-zlymeda
- pkg/mount/mountutil.go
- pkg/mount/mountutil_test.go
Some linux systems use device /dev/root as root filesystem, but /dev/root is not a real device. Thus symlink /sys/class/block/root does not exists and os-disk-exclude-filter fails to exclude os disk. If the symlink /sys/class/block/root does not exists, the real root disk is resolved from /proc/cmdline.
Detects real device behind /dev/root
No
* Spin up AWS EC2 (eg. m5d.xlarge using instance stores) with ubuntu 20.04
* install microk8s
* install helm
* install openebs using helm
* check the NDM logs:
* there is an error saying "/sys/class/block/root No such file or directory"
* the …
> fix(mount): detect real device when using /dev/root

- changelogs/unreleased/496-akhilerm
- pkg/partition/partition.go
As per the new UUID generation logic, a GPT partition will be created on
virtual disks. 
The following issue was faced in some scenarios: The iSCSI disk created by
OpenEBS was partitioned. This may have happened because, when NDM tried to
read the disk properties via udev, it was missing, therefore NDM created the
partition, resulting in data loss / corruption. But later those properties came up in the udev cache.
This fix adds an additional check for filesystem on the disk
before creating partitions.
No
**Any additional …
> fix(partition): add filesystem check on disk before creating partitions

- changelogs/unreleased/496-akhilerm
- pkg/partition/partition.go
as per the new UUID generation logic, a GPT partition will be created on
virtual disks. This fix adds an additional check for filesystem on the disk
before creating partitions.
The following issue was faced in some scenarios: The iSCSI disk created by
OpenEBS was partitioned. This may have happened because, when NDM tried to
read the disk properties via udev, it was missing, therefore NDM created the
partition. But later those properties came up in the udev cache.
cherry-pick #496
> cherry-pick(partition): check if filesystem exists on disk before creating partitions

- api-service/node/services/listBlockDevice.go
- cmd/ndm_daemonset/probe/smartprobe.go
- cmd/ndm_daemonset/probe/udevprobe.go
- pkg/sysfs/syspath.go
- pkg/udevevent/event.go
To add more verbose information into NDM daemon logs.
- add more verbose logs in udev probe
- log errors from sysfs package
No
This PR can be treated as a continuation of #489 
**Checklist:**
> fix(sysfs,udev): add additional verbose logs in udev probe

- .github/workflows/build.yml
- .github/workflows/pull_request.yml
- .github/workflows/release.yml
- .travis.yml
- Makefile.buildx.mk
- build/build.sh
Signed-off-by: shubham <shubham.bajpai@mayadata.io>
This PR fixes the below issues while building the images in buildx github actions
- In the build workflow the branch env is not set
```
Run make docker.buildx.ndm
make docker.buildx.ndm
make buildx.push.ndm
shell: /bin/bash -e {0}
env:
TAG: 0.9.0-RC2-ci
BRANCH: {BRANCH}
```
- In the release workflow the RELEASE_TAG is not set
```
Run make docker.buildx.ndm
make docker.buildx.ndm
make buildx.push.ndm
shell: /bin/bash -e {0}
env:
TAG: 0.9.0-RC2
RELEASE_TAG: 
```
- Adds an env to pass the IMAGE_ORG to the actions.
- Makes the build script independent of TRAVIS_TAG variable.
- Updates the buildx action to docker/setup-buildx-action@v1
**Any additional information for your reviewer?** : …
> chore(build): fix envs in github workflows

- build/ndm-daemonset/Dockerfile
- build/ndm-exporter/Dockerfile
- build/ndm-operator/Dockerfile
- changelogs/unreleased/503-xunholy
Signed-off-by: Michael Fornaro <20387402+xUnholy@users.noreply.github.com>
Updating Dockerfiles to use the `buildx` built-in ARGs will provide more flexibility to provide support for additional OS/ARCHS/ARM variants in the future. This also will create a cleaner and more maintainable Dockerfile moving forward.
https://docs.docker.com/engine/reference/builder/#automatic-platform-args-in-the-global-scope
**Checklist:**
> chore(build) Updating dockerfile(s) with buildx built-in ARGs

- changelogs/unreleased/504-akhilerm
- cmd/ndm_daemonset/app/command/device-list.go
- cmd/ndm_daemonset/probe/sysfsprobe.go
- Controller options were not set in the `devce list` command which caused the command to not list blockdevice resources. 
- The sysfsprobe was missing a return statement which resulted in processing of the device even if an error occurs.
- set controller options in device list command
- return sysfs probe to prevent null pointer exception
No
**Checklist:**
> fix(controller, probe): fix sysfs probe and controller options

- blockdevice/blockdevice.go
- changelogs/unreleased/495-akhilerm
- cmd/ndm_daemonset/filter/osdiskexcludefilter.go
- cmd/ndm_daemonset/probe/udevprobe.go
- cmd/ndm_daemonset/probe/udevprobe_test.go
- cmd/ndm_daemonset/probe/uuid.go
- cmd/ndm_daemonset/probe/uuid_test.go
- ndm-operator.yaml
- pkg/mount/mountutil.go
- pkg/udev/common.go
- pkg/udevevent/event.go
Adds DM support to NDM. With the changes in this PR: lvm, crypt, loop, dm devices will be natively supported in NDM.
- adds DM fields to blockdevice core struct
- add uuid generation algorithm for dm and loop devices
- add dm device support to os disk filter
No
`udevadm info` for dm devices (lvm and crypt)
```
k8s@worker-ak1:~$ udevadm info /dev/dm-0
P: /devices/virtual/block/dm-0
N: dm-0
S: disk/by-id/dm-name-vg0-lv0
S: disk/by-id/dm-uuid-LVM-j2xmqvbcVWBQK9Jdttte3CyeVTGgxtVV5VcCi3nxdwihZDxSquMOBaGL5eymBNvk
S: …
```
> feat(core, uuid): add dm support

- README.md
- _config.yml
- index.md
This PR adds helm chart install instructions to be displayed at the Github page. 
The page can be viewed at `openebs.github.io/node-disk-manager` after the PRs 
#491 and #488 are merged.
Signed-off-by: Ashutosh Kumar <ashutosh.kumar@mayadata.io>
> feat(gh-pages): add github page content

- changelogs/unreleased/500-ajeetrai707
- pkg/select/blockdevice/filters.go
- pkg/select/blockdevice/filters_test.go
This PR adds a filter that does not select
BD that has empty block device tag value.
Ref: https://github.com/openebs/openebs/discussions/3139
Signed-off-by: ajeetrai707 <ajeetrai707@gmail.com>
**Checklist:**
> feat(blockdevicefilter): add filter for empty block device tag label value

- .github/workflows/build.yml
- .github/workflows/release.yml
Use the official docker action instead 
- use official docker login action in workflows
- use access token instead of password for dockerhub
**Checklist:**
> chore(build): use official docker login actions

- .github/workflows/build.yml
- .github/workflows/release.yml
- Makefile
- Makefile.buildx.mk
- build/ndm-daemonset/Dockerfile
- build/ndm-exporter/Dockerfile
- build/ndm-operator/Dockerfile
Github actions [deprecated](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/) the set-env command. Instead of that environment files are the recommended option now.
Additionally, there is an issue with setting RELEASE_TAG inside the buildx container, which needs to be fixed for proper
version to be passed as ldflags.
- use environment files in github actions instead of deprecated set-env command
- pass RELEASE_TAG as build arguments to buildx container.
No
**Any additional …
> chore(build): fix build script and remove deprecated methods

- deploy/ndm-operator.yaml
- deploy/yamls/ndm-cluster-exporter.yaml
- deploy/yamls/ndm-node-exporter.yaml
- deploy/yamls/node-disk-manager.yaml
- deploy/yamls/node-disk-operator.yaml
- pkg/mount/mountutil.go
- pkg/mount/mountutil_test.go
NDM is crashing on new GKE setups due to a failure in parsing the `/proc/cmdline` file. This issue occurs when the file contains a root partition entry like `root=/dev/dm-0`, where the identifier type is not present
- adds additional check of no.of items in the `root=` line while parsing
- fix service account in ndm yamls
**Checklist:**
> fix(mount): fix parsing /proc/cmdline

- changelogs/unreleased/516-akhilerm
- changelogs/unreleased/518-akhilerm
- cmd/ndm_daemonset/filter/pathfilter.go
- cmd/ndm_daemonset/filter/pathfilter_test.go
- cmd/ndm_daemonset/probe/udevprobe.go
- pkg/udev/common.go
Most systems use a configured `/dev/mapper/<dm-name>` rather than the `/dev/dm-X` to identify dm devices. NDM was only checking for `/dev/dm-X` path in the path filter which caused issues as mentioned [here](https://github.com/openebs/openebs/issues/3310)
- adds check for /dev/mapper along with device path in path filter
No
**Checklist:**
> fix(filter): add check for /dev/mapper path along with /dev/dm- in path filter

- changelogs/unreleased/516-akhilerm
- changelogs/unreleased/517-akhilerm
- cmd/ndm_daemonset/probe/eventhandler.go
- cmd/ndm_daemonset/probe/eventhandler_test.go
When one of the disk is bad in the node / NDM is not able to create blockdevice resource for the disk, NDM repeatedly performs the rescan operation, skipping the other disks. This results in some disks not being processed. This PR brings in a change to wait till all the disks are processed, before starting the rescan.
- adds a check to skip processing of blockdevices if the parent or any of the slave devices of the given block device has errored out.
NOTE: This commit does not change the continuous rescan that NDM will do incase of a disk erroring out.
**Any additional information …
> fix(eventhandler): continue processing indepedent blockdevices even if one device fails

- changelogs/unreleased/519-akhilerm
- cmd/ndm_daemonset/filter/devicevalidityfilter.go
- cmd/ndm_daemonset/filter/devicevalidityfilter_test.go
Repeated udev scan sometimes misses certain fields for devices like partition uuid, dm uuid etc. Since these fields are mandatory for generating the blockdevices unique ID, not having these fields may have issues with wrong blockdevices being created.
- adds a new check in the device validity filter to make sure that only devices with a valid partition UUID or dm UUID are used for creating blockdevice resources.
No
**Checklist:**
> fix(filter): add partition and device mapper check to validity filter

- .github/workflows/release.yml
This is required so that chart releases does not trigger a release workflow.
- modify release workflow to run only when tags with `v` prefix are pushed.
No
**Checklist:**
> fix(action): fix release workflow to run only tags with `v` prefix

- changelogs/unreleased/524-akhilerm
- cmd/ndm_daemonset/filter/osdiskexcludefilter.go
- pkg/features/features.go
- pkg/mount/mountutil.go
- pkg/mount/mountutil_test.go
Sometimes the nodes may have only one large disk with many partitions. NDM currently ignores the complete disk if it contains a system partition. This PR adds support to create blockdevice resources from the unused partitions on the OS disk.
- adds a new feature gate to enable / disable using OS disk for blockdevices
- modify the os disk filter to exclude only the partition that contains the system mountpoints and not the entire disk
No
**Checklist:**
> feat(filter): add support to use unused partitions in os-disk

- blockdevice/blockdevice.go
- changelogs/unreleased/523-akhilerm
- cmd/ndm_daemonset/probe/seachestprobe.go
- cmd/ndm_daemonset/probe/sysfsprobe.go
- pkg/seachest/seachest.go
- pkg/sysfs/syspath.go
- pkg/sysfs/syspath_test.go
- add unknown drive type to blockdevices. This will be used instead of the empty string. While adding the crd validation we came across this case which failed validation due to code setting to blank. Instead of blank, if we provide Unknown it will be better in terms of readability and validation.
No, upgrades are automatically handled
**Checklist:**
> fix(probe): add unknown drive type

- changelogs/unreleased/493-RealHarshThakur
- changelogs/unreleased/527-akhilerm
- pkg/cleaner/config.go
- pkg/cleaner/jobcontroller.go
- pkg/env/env.go
- pkg/env/env_test.go
add image pull secret to cleanup job pod via env
No
- provided the env with image pull secrets in the ndm operator deployment spec, claimed a blockdevice and then unclaimed it. 
- claimed-unclaimed device without providing any env variable for image secrets.
**Checklist:**
> feat(cleanup): support image pull secrets for cleanup pod

- changelogs/unreleased/493-RealHarshThakur
- changelogs/unreleased/527-akhilerm
- pkg/cleaner/config.go
- pkg/cleaner/jobcontroller.go
- pkg/env/env.go
- pkg/env/env_test.go
add image pull secret to cleanup job pod via env
cherry-pick #527
> cherry-pick(cleanup): support image pull secrets for cleanup pod (#527)

- blockdevice/blockdevice.go
- changelogs/unreleased/530-akhilerm
If `mpath` is not added to supported type, NDM will not use the `DM_UUID` to create a blockdevice UUID, resulting in device identification erroring out.
- add multipath device type to supported DM device types
No
**Checklist:**
> feat(blockdevice, core): add mpath to supported DM device types

- changelogs/unreleased/537-z0marlin
- cmd/ndm_daemonset/probe/sysfsprobe.go
sysfsprobe fetches logical/physical blocksize, hw sector size,
and drive type from sysfs using `<syspath>/queue` directory.
This directory is available only for parent disks and not partitions.
These details for partitions are same as their parent disks. Use
their parent disks to fetch the details.
Manually tested by running in a minikube cluster
**Checklist:**
> fix(probe): fetch block size and drive type for partitions

- changelogs/unreleased/539-z0marlin
- cmd/ndm_daemonset/probe/mountprobe.go
- pkg/mount/mountinfo.go
The `Identifier.DeviceBasicMountInfo()` fetches mount attributes of a
device by reading the mounts file. The path of this file is currently
fixed. Pass the file path as a parameter to the function. This will
provide more flexibility in the code and also ease writing unit tests
for code that uses this function. The default path is exported as a
constant, and can still be used.
This PR is a part of the changes required to solve #253, as discussed on slack with @akhilerm 
**Checklist:**
> refactor(mount): pass file path as parameter in DeviceBasicMountInfo()

- changelogs/unreleased/538-akhilerm
- cmd/ndm_daemonset/probe/addhandler.go
- cmd/ndm_daemonset/probe/eventhandler.go
When a filter excludes the parent disk and includes the partition, it caused to NDM error out, because the parent disk was not added in the hierarchy cache. This PR adds the device into the hierachy cache irrespective of whether it is filtered or not. This removes issues while such filter configurations are provided.
- add device to hierarchy cache before filtering
No
- tested with the scenario mentioned in openebs/openebs#3321
_Mention if this PR is part of any design or a …
> fix(eventhandler): add all devices to hierarchy before filtering

- cmd/ndm_daemonset/probe/eventhandler_test.go
- cmd/ndm_daemonset/probe/udevprobe_test.go
- pkg/udev/mockdata.go
Github actions has made certain changes in VM configurations which was causing unit tests which make use of OS disk to fail.
The changes in the Github actions VM are:
1. ubuntu-latest now uses ubuntu-20.04 instead of ubuntu-18.04
2. OS disk is now mounted at `/dev/root`
3. Devlinks are appearing in different order in udev 
1. use `/proc/cmdline` to get mount point if `/proc/self/mounts` fails
2. use separate function to compare devlinks to compare links that are unordered
No
**Any additional information for your reviewer?** : …
> fix(test): fix unit tests to support /dev/root

- changelogs/unreleased/546-cospotato
- pkg/udevevent/event.go
When I unplugged a disk from node, the BlockDevice was not become Inactive  immediately until I restart (delete daemonset pod) the daemonset on the node.
fix cannot deactive BlockDevice when GPTBasedUUID is enabled
**Checklist:**
> fix(event): fix cannot deactive BlockDevice

- pkg/udev/common_test.go
use unordered comparison for comparing string array of devlinks as devlinks order can change
No
Continuation of https://github.com/openebs/node-disk-manager/pull/547
**Checklist:**
> fix(tests): fix unit test that uses devlinks

- .github/workflows/build.yml
- .github/workflows/pull_request.yml
- README.md
- RELEASE.md
- build/build.sh
- build/push
- add load option to pull request workflow so images that are built during integration-tests are loaded into the local docker daemon before running the tests
- fix image name in build workflow for node-disk-operator
- fix docs and scripts that uses travis variables.
No
Continuation of https://github.com/openebs/node-disk-manager/pull/548
**Checklist:**
> fix(workflow): add load option and fix image tag

- .github/workflows/release.yml
- Makefile
- use ${{ env.RELEASE_TAG }} instead of ${RELEASE_TAG} as they are expanded only in a shell
No
continuation of #553 
**Checklist:**
> chore(workflow): use RELEASE_TAG from env in github actions

- changelogs/unreleased/560-akhilerm
- pkg/sysfs/device.go
- pkg/sysfs/device_test.go
If the devpath received due to some error is empty, then sysfs device creation caused a crash. This PR adds a check for empty path before creating a sysfs device.
- adds check for empty device path
No
**Checklist:**
> fix(sysfs): add check for empty devpath

- .github/workflows/build.yml
- .github/workflows/pull_request.yml
This condition in the .github/workflows/build.yml file will ignore pushes made to `docs/` and `deploy/helm/` directories and avoid building the images.
Signed-off-by: Niladri Halder <niladri.halder@mayadata.io>
> chore(github-action): Avoid builds for pushes to helm chart and docs files

- changelogs/unreleased/590-z0marlin
- cmd/ndm_daemonset/probe/mountprobe.go
- pkg/mount/mountinfo.go
- pkg/mount/mountutil.go
- pkg/mount/mountutil_test.go
Partitions can be mounted at multiple points in a given system.
Return a list of all the mount points of a given device as found in the
mounts file instead of just returning the first entry.
**Checklist:**
> fix(pkg, mount): fetch all mount points for a given device

- changelogs/unreleased/593-z0marlin
- cmd/ndm_daemonset/probe/udevprobe_test.go
- pkg/sysfs/syspath_test.go
changes made:
- fix sysfs tests to cleanup after finishing. tests were failing when
run the second time after passing for the first time.
- skip `TestUdevProbe` in package probe if disk uuid cannot be
generated
- fix `TestFillDiskDetails` in package probe to correctly set
expected dev links
**Checklist:**
> fix(tests): fix buggy tests in probe and sysfs

- .github/workflows/release.yml
Signed-off-by: shubham <shubham.bajpai@mayadata.io>
This PR addresses the issue where a release workflow is triggered when a helm chart is released. The images pushed have tags with the name of the chart like [`openebs-ndm-1.5.0`](https://github.com/openebs/node-disk-manager/actions/runs/943536118) in this case. We should avoid building images in such cases. The if condition added in the workflow prevents such workflows from executing.
**Checklist:**
> fix(actions): skip release workflow on helm release

- changelogs/unreleased/601-z0marlin
- cmd/ndm_daemonset/controller/probe.go
- cmd/ndm_daemonset/controller/probe_test.go
- cmd/ndm_daemonset/probe/eventhandler.go
event messages passed in the `UdevEventMessageChannel` channel are used
to trigger actions in the controller to add/update/delete blockdevices.
In case of addition, the controller runs all the registered probes to
fill certain details of the blockdevice. While all probes need to be run
when adding a new blockdevice, in case of updates, the list of probes to
be run can be narrowed down based on the type of update. For example,
when the mount points of a partition change, mount probe alone is enough
to fetch the new information.
add an allowlist for probes in the event message to inform the
controller what probes are to be run. the controller then runs only the
probes that are enabled and available in the allowlist. leaving the
allowlist empty causes default behaviour which is to run all …
> feat(controller): selectively run probes using allowlist in event msg

- changelogs/unreleased/602-z0marlin
- cmd/ndm_daemonset/probe/addhandler.go
when adding a blockdevice, the information stroed in the controller
cache does not contain the the up to date uuid of the bd generated while
adding the bd. Update the bd cache with the new uuid after generation.
**Checklist:**
> fix(probe): update bd cache after generating uuid

- cmd/manager/main.go
since the default sync period was not set, the resources were not getting reconciled incase of successful reconciliation. 
- sets the sync period to 30 seconds so that the resources are reconciled frequently
**Checklist:**
> fix(manager): set reconciliation interval for manager

- docs/mount-change-detection.md
> docs: add mount change detection design

- deploy/ndm-operator.yaml
- deploy/yamls/ndm-cluster-exporter.yaml
- deploy/yamls/ndm-node-exporter.yaml
The ndm cluster exporter and ndm node exporter service were not be to discover/identify the endpoints because of being installed in different ns then the ndm-manager daemonset and ndm-operator deployment through operator.
This PR adds namespace field in the metadata section to the service same as the namespace in which the ndm-manager daemonset and ndm-operator deployment  is installed to that the service is able to successfully identify its endpoints.
No.
_Mention if this PR is part of any design or a continuation of previous …
> fix(endpoints-discovery): Fixed ndm exporter's service endpoints discovery

- integration_tests/sanity/ndm_integration_test.go
ndm logs are necessary to debug issues with integration tests. print the
ndm pod logs if a test fails
there have been multiple flaky integration test runs in the ndm ci pipeline. There's an open issue to fix these tests (#625). However, it is difficult to debug the test runs on github ci since the ndm logs aren't available. This PR aims to solve the problem.
**Checklist:**
> tests(integration): print ndm logs if an integration test fails

- changelogs/unreleased/616-z0marlin
- cmd/ndm_daemonset/probe/changehandler.go
- cmd/ndm_daemonset/probe/eventhandler.go
- cmd/ndm_daemonset/probe/mountprobe.go
- cmd/ndm_daemonset/probe/sysfsprobe.go
- cmd/ndm_daemonset/probe/udevprobe.go
- deploy/ndm-operator.yaml
- deploy/yamls/node-disk-manager.yaml
- integration_tests/sanity/customresources_test.go
- integration_tests/sanity/size_change_test.go
- integration_tests/udev/disks.go
- integration_tests/yamls/node-disk-manager.yaml
- pkg/epoll/epoll.go
- pkg/features/features.go
Add blockdevice size change detection using udev change events
**Checklist:**
> feat(probe): add size change detection

- cmd/ndm_daemonset/controller/controller.go
- cmd/ndm_daemonset/probe/usedbyprobe.go
- pkg/blkid/blkid.go
Signed-off-by: liuminjian <liuminjian@chinatelecom.cn>
#638 Enhance the details storage on BD when the device has zpool
1. add file type field for zfs block device
2. add zpool name label for zfs block device
**Checklist:**
Where:
* …
> Enhance the details storage on BD when the device has zpool
